### ISSUE TITLE
CONFIG key of parameter definitions

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#100]
My understanding is that the content of the global/params section of parameter configuration files internally is moved to a Robot Framework list of global parameters.

Within a robot file I used the keyword `Get Variables` to get a dictionary of all variables at runtime. This works, but this dictionary contains a key `CONFIG` with value of type

`<class 'RobotFramework_TestsuitesManagement.Config.CConfig.dotdict'>`

This `CONFIG` dictionary contains the top level keys of parameter configuration files (like `WelcomeString` and `TargetName`). And also an empty `'params': {}`.

These top level keys are not part of the global parameter list immediately.

Here I have some doubts. It is not really clear to me why such a differentiation is made. It also causes effort to explain this to the users.

In tutorial I explained that some parameters have to be accessed in this way:

`${CONFIG}[Maximum_version]`

and others in this way:

`${teststring}`

If would be more user friendly if this would not be necessary. 

Is there a possibility to merge the values to one common dictionary?

**Comment by namsonx** [comment]
Hello Holger,

We design all parameters which are defined in global/params section of configuration file will be set as ROBFW global variables, and the general information of Robot test project (the top level keys of parameter configuration file) will be store in CONFIG dictionary object.

"Is there a possibility to merge the values to one common dictionary?": Yes, we can. But with this solution users have to access configuration parameters via a common dictionary instead of accessing directly as current method.

Thank you,
Son

**Comment by HolQue** [comment]
No, no, other way round: Why keeping parts of the parameters in `CONFIG`? Why not moving them also to the already available list of global parameters?

Within test code this would enable this

`${Maximum_version}`

instead of the currently required

`${CONFIG}[Maximum_version]`

My question still is: Why those differences in parameter access?

**Comment by test-fullautomation** [comment]
Hi both,
please do no change here.
Most is intended. 
We can discuss if this implementation it is meaningful, but the current implementation follows the requirement.

Only the empty  `'params': {}`  dict is wrong. This need to be removed.

So, other changes than empty params dict let us discuss before we change.

Thank you,
 Thomas

**Comment by namsonx** [comment]
> 

Hello Thomas,

You mean will remove 'params': {} and just kept 'global': {} to define the global variables of robot run?
For this we will inform our current users change their configuration file format or we will implement to accept both configuration file formats?

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
please wait before any change, we need to talk about this some minutes to avoid misunderstandings.
Thank you,
 Thomas
