### ISSUE TITLE
Variant name without variant configuration file

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#105]
In command line I selected a variant with name variant2

`--variable variant:"variant2"`

But by mistake I forgot to pass a variant configuration file to the suite setup.

The RobotFramework_TestsuitesManagement runs with configuration level 4 in this case. That is like expected, but unfortunately the variant name in command line is ignored completely.

Is it possible to detect this combination? It would be helpful to have an error message like this:

`Not able to get a configuration for variant '<variant name>' because of a variant configuration file is not available.`

Followed by the usual

`WARN - Running with configuration level 4! `

**Comment by test-fullautomation** [comment]
In general:
The handed over variant need to be checked if it is existing in the configuration file.
If not, then an error need to be logged, and the possible variants (from the configuration file).

In this we need to raise an error that a configuration file is missing if there is no level 2 configuration (as part of the test) existing.

**Comment by namsonx** [comment]
Hello Thomas and Holger,

I created the pull-request #123 for this ticket, the error message in this scenario looks like below:

    ==============================================================================
    Exercise-06
    ==============================================================================
    [ ERROR ] The variant variable is defined when executed robot with the value 'variant2', but there is no variant configuration file in RobotFramework_TestsuitesManagement.testsuite_setup  
              In case you want to execute robot with configuration level2 with variant 'variant2':
                 - Please put the path of the variant configuration file as the input parameter of RobotFramework_TestsuitesManagement.testsuite_setup
    
    Test Case exercise-06 :: exercise-06                                  | UNKNOWN |
    Parent suite setup unknown:
    Unknown exception occurs. Details: Loading configuration level 2 failed!
    ------------------------------------------------------------------------------
    Exercise-06                                                           | UNKNOWN |
    Suite setup unknown:
    Unknown exception occurs. Details: Loading configuration level 2 failed!
    
    1 test, 0 passed, 0 failed, 1 unknown
    ==============================================================================
    Debug:   C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\debug_log.log
    Output:  C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\output.xml
    Log:     C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\log.html
    Report:  C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\report.html

Thank you,
Son

**Comment by namsonx** [comment]
Hello Thomas and Holger,

I created the pull-request #123 for this ticket,

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and already merged with #123
