### ISSUE TITLE
Preprocessor definitions in robot_schema.json

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#112]
The file robot_schema.json still contains preprocessor definitions:

```
"preprocessor": {
  "definitions": {
  }
}
```
Why? My understanding is that RobotFramework_TestsuitesManagement does not support preprocessor definitions. But if the schema allows this we run into danger, that someone uses this - with the outcome that the content is ignored and the user gets no feedback.

What is not computed and not wanted, should not be allowed.

**Comment by test-fullautomation** [comment]
Hi Son,
we should always hide future functionality as long it's not completely implemented.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas and Holger,

I created the pull-request #118 for this ticket.

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and already merged with #118
