### ISSUE TITLE
Possible improvement of meta data handling

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#127]
`CConfig.py` contains the following code:

```
rMetaData      = CStruct(
                            sVersionSW = '',
                            sVersionHW     = '',
                            sVersionTest   = '',
                            sROBFWVersion  = get_full_version('Robot Framework')
                        )
```
together with:

```
if "version_sw" in suiteMetadata and self.rMetaData.sVersionSW == '':
    pass
else:
    BuiltIn().set_suite_metadata("version_sw", self.rMetaData.sVersionSW, top=True)
if "version_hw" in suiteMetadata and self.rMetaData.sVersionHW == '':
    pass
else:
    BuiltIn().set_suite_metadata("version_hw", self.rMetaData.sVersionHW, top=True)
if "version_test" in suiteMetadata and self.rMetaData.sVersionTest == '':
    pass
else:
    BuiltIn().set_suite_metadata("version_test", self.rMetaData.sVersionTest, top=True)
```

My impression is that this is very long winded.

This is much shorter - and should also work:

```
for parameter in ("version_sw", "version_hw", "version_test"):
    BuiltIn().set_suite_metadata(parameter, "", append=True, top=True)
```

And it is also possible, to use the same method in the same file to make a dump of all metadata.

I tried the following use case:

- `version_test` not defined
- `version_hw` defined within robot file as Metadata within `*** Settings ***`
- `version_sw` defined within command line with: `--metadata version_sw:metadata_version_sw_in_command_line`
- `my_test_local_metadata` defined within robot file as Metadata within `*** Settings ***`

Outcome in debug log:

```
Set suite metadata 'project' to value 'RobotFramework Testsuites'.
Set suite metadata 'machine' to value '...'.
Set suite metadata 'tester' to value '...'.
Set suite metadata 'testtool' to value 'Robot Framework 4.1.3 (Python 3.9.16 on win32)'.
Set suite metadata 'version' to value '0.6.0'.
Set suite metadata 'version_sw' to value 'metadata_version_sw_in_command_line '.
Set suite metadata 'version_hw' to value 'metadata_version_hw_within_file '.
Set suite metadata 'version_test' to value ''.
Entire meta data available during test execution:
Meta data 'machine' = '...'
Meta data 'my_test_local_metadata' = 'my_test_local_metadata_value_within_file'
Meta data 'project' = 'RobotFramework Testsuites'
Meta data 'tester' = '...'
Meta data 'testtool' = 'Robot Framework 4.1.3 (Python 3.9.16 on win32)'
Meta data 'version' = '0.6.0'
Meta data 'version_hw' = 'metadata_version_hw_within_file '
Meta data 'version_sw' = 'metadata_version_sw_in_command_line '
Meta data 'version_test' = ''
```
This is the alternative code:

```
suiteMetadata = BuiltIn().get_variables()['&{SUITE_METADATA}']

BuiltIn().set_suite_metadata("project"  , self.sProjectName, top=True)
BuiltIn().set_suite_metadata("machine"  , self.__getMachineName(), top=True)
BuiltIn().set_suite_metadata("tester"   , self.__getUserName(), top=True)
BuiltIn().set_suite_metadata("testtool" , self.rMetaData.sROBFWVersion, top=True)
BuiltIn().set_suite_metadata("version"  , VERSION, top=True)

# additional parameters that shall be present even in case the user does not set a value
# (but if already a value is available, this value shall not be overwritten)
for parameter in ("version_sw", "version_hw", "version_test"):
    BuiltIn().set_suite_metadata(parameter, "", append=True, top=True)

# output of entire metadata:
BuiltIn().log("Entire meta data available during test execution:")
suiteMetadata_updated = BuiltIn().get_variables()['&{SUITE_METADATA}'] # !!!
for md_parameter, value in suiteMetadata_updated.items():
    BuiltIn().log(f"Meta data '{md_parameter}' = '{value}'")
```

I cannot be sure not to overlook any side effect. Please check this code carefully (and give it a chance ;-).

**Comment by HolQue** [comment]
Should solve:
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/102

See also:
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/103#issuecomment-1431245925

**Comment by HolQue** [comment]
Much more complicated than I expected!

There is a difference between "suite" and "top level suite". Meta data in command line (by `--metadata`) are at top level.

Values defined with `set_suite_metadata(...)` are at top level only with `top=True` (like done in testsuites management).

Meta data values defined in `Settings` within a robot file seems to be local (= not at top level).

OK so far. But the Robot Framework documentation only gives a hint about the existence of this switch `top` - without any explanation about meaning and impact.

Side effects: In case of a single robot file is executed, there seems not to be a concrete difference between "local" and "top level". All together is stored in `SUITE_METADATA`. But when I execute a folder containing robot files, it's completely different:

When printing the content of `SUITE_METADATA` in `CConfig.py`, then only the local metadata are printed - and not the top level meta data values any more. I added the code to print the values also to the `testcase_setup` in `CSetup.py` - and I called this `testcase_setup` in my robot file. The outcome is: I have only the local values printed out now two times. But the top level ones are lost completely.

OK, I stop this now.

Two aspects:

1. We urgently need to learn more about the scopes of meta data (depending of a single file or a folder is executed) and about how the Robot Framework handles the values.
2. We need to clarify our requirements.

Only when this is clarified we have a chance to modify the code in an meaningful way.

**Comment by HolQue** [comment]
OK, I try once again to get clarity:

* In suite setup we need to find a way to get access to top level meta data (in both cases: a single file is executed and a folder is executed).
* We need to find a way to distinguish already in the suite setup between top level values and local values.
* In suite setup we print only the top level values - under an unmistakable headline (e.g. Suite metadata value:).
* In test setup we need to find a way to get access to top level values. We print at first the top level values - also under the same unmistakable headline like used in the suite setup. This is a repetition only, but helpful (user has no need any more to scroll up to find the top level values.
* In test setup we print in a second step all other meta data values, that are known in the scope of the current test only (the local ones). Also under an unmistakable headline (e.g. Local meta data value:).

Finally we have to clarify how we can consider all other parameters e.g. the ones provided by testsuites management, in this concept also.

**Comment by HolQue** [comment]
Once more:

With `--metadata` I define a value in command line.
With `Metadata` I define another value inside the robot file.

Within the robot file I log the content of `{SUITE_METADATA}`.

Try 1: I execute the robot file
Try 2: I execute the folder containing this robot file

Outcome:

If I execute the robot file, `{SUITE_METADATA}` contains both values.
If I execute the folder, `{SUITE_METADATA}` contains the value defined inside the robot file only (but not the value defined in command line; and also not the values defined by the testsuites management! - most probably because they are at the same level: the top level).

But even in this second case all values are listed in the XML version of the log file. This means we run into trouble if we want to have access to all meta data with the help of `{SUITE_METADATA}` inside a test, but the automated logging
(that writes all other informations to the XML log file) is not affected - and therefore this limitation does not have a negative impact to our database applications (luckily).

In internet I found a really nice solution:

With such an `__init__.robot` file:

```
*** Settings ***
Suite Setup       Store Top Suite Metadata

*** Keywords ***
Store Top Suite Metadata
    Set Suite Variable   ${TOP SUITE METADATA}    ${SUITE METADATA}    children=True
```
I still get the local values only with `${SUITE METADATA}`.
But with `${TOP SUITE METADATA}` I get the top level values.

This means we have a chance to log both in debug log file.

The next step would be to port this code (as pure Python) to the testsuites management.

I gave it a try, but I was not able to set `children=True` at Python level (got errors).

**Comment by namsonx** [comment]
Hello Holger,

As you already known, ROBFW could be triggered at robot file level or at directory level which can contains many robot files and sub-directories. We could set metadata for every robot file (defines in ```*** Settings ***```) or set metadata for a directory (creates ```__init__.robot``` in the directory then defines in ```*** Settings ***``` of ```__init__.robot```).

The following definition:
```
rMetaData      = CStruct(
                            sVersionSW = '',
                            sVersionHW     = '',
                            sVersionTest   = '',
                            sROBFWVersion  = get_full_version('Robot Framework')
                        )
```
aims to define and set a metadata at highest level when executing Robot test with TestsuitesManagement.

I created a small improvement in commit [0c3c8117b0dbd](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/commit/0c3c8117b0dbdf5ac53a6ac9edd3f9ba803566ea) 

Could you please help me check this ticket again?

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
