### ISSUE TITLE
Still "Unknown" exceptions

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#133]
Console still contains "Unknown" exceptions. Caused by

```
def _get_message(self):
    msg = "Unknown exception occurs. "
    if self.msg:
        msg = msg + self.msg
    if self.details:
        if msg[-1] != '.' and msg[-2:] != ". ":
            msg += '. '
        msg += "Details: %s" % self.details
    return msg
```

in `errors.py`

We have already discussed that the exception itself should not be named "Unknown".

And the code of this method is really long winded. Most of the code belongs to punctuation. Really, this should not be necessary.

Also the printed messages `self.msg/self.details` contain already final "!". Therefore an additional dot at the end is not necessary.

Please give it a try with the following alternative version of this method, that is much easier to understand:

```
def _get_message(self):
    listMsg = []
    if (not self.msg) and (not self.details):
        listMsg.append("Exception occurred.")
    if self.msg:
        listMsg.append(f"{self.msg}")
    if self.details:
        listMsg.append(f"Details: {self.details}")
    return "\n".join(listMsg)
```

This issue is similar to

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/114

**Comment by test-fullautomation** [comment]
Hi Cuong,
you  made the change in our meeting, but I did not get a pull-request.
Please provide a pull-request as soon as possible.
Thank you,
 thomas
