### ISSUE TITLE
Invalid command line causes Python error

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#134]
By mistake I pass a parameter configuration file to the command line parameter `local_config`.

A variant configuration file is not involved.

Outcome is the following error message that looks worryingly:

`RecursionError: maximum recursion depth exceeded while calling a Python object`

The test is not executed (like expected) but the test result is FAIL (I would expect UNKNOWN).

**Comment by test-fullautomation** [comment]
Hi Son,
what is the status of this issue?
Thank you,
 Thomas

**Comment by HolQue** [comment]
TSM_0150 and TSM_0151 temporarily commented out; needs to be undone after fix.

Regarding the error scenario "invalid command line" I suggest to consider also

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/95#issuecomment-1562495271
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/95#issuecomment-1562532641

while fixing the issue.

**Comment by namsonx** [comment]
Hello Holger, Hello Thomas,

I created the pull-request #194 for the improvement.
@HolQue : Could you please help me review the log output I made in my pull-request?

Thank you,
Son

**Comment by HolQue** [comment]
Issue is solved and can be closed.
