### ISSUE TITLE
Schema file name unfavorable

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#136]
I have some doubts regarding the file name:

`RobotFramework_TestsuitesManagement\Config\robot_schema.json`

Because this schema file has nothing to do with the Robot Framework immediately. This file is only related to JSON configuration files of the Testsuites Management. Also in error messages this file is named: "`configuration JSON schema file`".

Therefore I propose to rename the file to "`configuration_schema.json`".

**Comment by test-fullautomation** [comment]
Hi Son,
is this issue solved?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger and Thomas,

I created the pull-request #176 for this ticket.

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and already merged with#176
