### ISSUE TITLE
Interference between global parameters and root node parameters

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#138]
For a certain variant I create a configuration file that defines in a first step a parameter named `teststring_common`.

In a second step I import another configuration file in which I use this parameter in the following two ways:

```
${params}['global']['teststring_common'] : "value 1",
"teststring_common" : "value 2"
```

Within the robot file I print the value of this parameter:

`Log    teststring_common : ${teststring_common}`

Outcome: `teststring_common` has value "`value 1`".

I comment out the first line.

Outcome: `teststring_common` has value "`value 2`".

Impact: `teststring_common` is accessible by `${teststring_common}` even if this parameter is defined in root node.

**Comment by namsonx** [comment]
Hello Holger,

We were defined the syntax ${...} to allow users overwrite a element of json configuration file, so I implemented jsonpreprocessor like:
     - Load all import files and combine them into 1 Json file.
     - Parse combined Json file into Json object, then loading all normal elements as global variables.
     - Check the elements which is in ${...} format, and overwrite the values.

It means normal elements of Json file are loaded first, then overwritten elements are checked and handled. That the reason you observed the log output as you mentioned.


"Impact: teststring_common is accessible by ${teststring_common} even if this parameter is defined in root node."
I confuse why the schema check mechanism does not work in case you defined teststring_common in root node?

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

I guess that the issue is from before the schema check has been introduced/adapted. I just executed this uses case again with the latest sources and I got a proper error message about a failed schema check.

This issue can be closed.

**Comment by test-fullautomation** [comment]
very good! I wondered already because sometime ago we defined that new variables at root level should be not allowed.
