### ISSUE TITLE
Error message improvement

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#139]
Current error message:

`[ ERROR ] The parameter 'WelcomeString' is a required property, but it's not set in JSON configuration file.`

I would like to have more weight on the fact that something is missing than on the fact that something is required.

And that something is missing implies already that this is required. This kind of redundancy can be avoided.

I suggest to use an error message like this:

`[ ERROR ] Missing parameter 'WelcomeString' in parameter configuration file <path and name of file>.`

**Comment by HolQue** [comment]
Another one:

`[ ERROR ] Loading of JSON configuration file failed! Reason: json file '...testfiles/config/tsm-test_config_syntax_error_within_import.json': 'json file '...testfiles\config\tsm-test_config_common_with_syntax_error.json': 'Expecting property name enclosed in double quotes: line 19 column 4 (char 120)''
`
This one liner is difficult to read. Some line breaks in between would be helpful.

**Comment by test-fullautomation** [comment]
Hi Son,
is this issue solved?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger and Thomas,

I created the pull-request #175 for this ticket.

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and already merged with #175
