### ISSUE TITLE
How about lists within JSON configuration files?

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#142]
I tried to create a list out of already existing parameters:

```
"list_val" : [${params}['global']['teststring_variant'],
              ${params}['global']['int_val'],
              ${params}['global']['float_val']],
```

Outcome: The loading failed with following error message:

`Expecting ',' delimiter`

Just playing with possibilities I put all values in quotes - expecting to get strings only:

```
"list_val" : ["${params}['global']['teststring_variant']",
              "${params}['global']['int_val']",
              "${params}['global']['float_val']"],
```

Outcome: This is accepted, but the log output contains a `str` cast (that should not be part of the log output):

`str(${params}['global']['teststring_variant'])`

Finally I removed the dollar operators to avoid having further syntax elements inside the strings:

```
"list_val" : ["{params}['global']['teststring_variant']",
              "{params}['global']['int_val']",
              "{params}['global']['float_val']"],
```

Outcome: This is accepted without issues and the log output is the same than in the definition:

```
{params}['global']['teststring_variant']
{params}['global']['int_val']
{params}['global']['float_val']
```

But nevertheless, the goal was to put already existing parameters into a list.

**Is this allowed?**

If not, I would prefer to have a more meaningful error message than:

`Expecting ',' delimiter`

**Comment by test-fullautomation** [comment]
Hi Son,
is this issue solved?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Retest done. Issue solved. Can be closed.
