### ISSUE TITLE
Value not updated in imported file

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#143]
A JSON configuration file contains the definition of a string parameter:

`"certain_teststring" : "initial value of certain teststring",`

Also a dictionary is available and the value of the string parameter is assigned to one of the subkeys of the dictionary:

`${params}['global']['dict_val']['key_2']['subkey_23']['subsubkey_231'] : ${params}['global']['certain_teststring'],`

After this assignment another configuration file is imported. This imported file imports another file.

And in this imported file I do two things:

At first I overwrite the string value:

`${params}['global']['certain_teststring'] : "updated value of certain teststring (2.1.1)",`

At second I use the updated string to update also the dictionary key:

`${params}['global']['dict_val']['key_2']['subkey_23']['subsubkey_231'] : ${params}['global']['certain_teststring']`

Within the executed robot file I log both parameters. Outcome:

The value of `certain_teststring` is: `updated value of certain teststring (2.1.1)`   (_like expected_)

The value of `subsubkey_231` is: `initial value of certain teststring` (_not expected_)

I would expect here that the `subsubkey_231` has the same value than `certain_teststring`.

**Comment by HolQue** [comment]
Addendum:

I went through the same use case again - like described above. But now I used a list, instead of a test string:

`"list_val" : ["initial list", 1, 2.2, "A", true, True, false, False, None, null],`

With the same outcome: Also the list is not updated.

**Comment by namsonx** [comment]
Hello Holger,

This issue occurs due to the issue in python-jsonpreprocessor package, it was fixed in jsonpreprocessor package. Could you please help me check again.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Holger,
can I close this issue?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Retest done. Issue solved. Can be closed.
