### ISSUE TITLE
Still brackets missing in error message

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#144]
Current format of error message:

`Reason: The variable 'params['global']['dTestDict']['I-am-not-existing']' is not available!`

Brackets around `params` missing.

Expected:

`Reason: The variable '{params}['global']['dTestDict']['I-am-not-existing']' is not available!`

**Comment by test-fullautomation** [comment]
Hi Son,
is this issue solved?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger and Thomas,

This error message is handled in JsonPreprocessor package.
I had created the pull-request https://github.com/test-fullautomation/python-jsonpreprocessor/pull/62 for this ticket.

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and already merged with [#62](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/62)
