### ISSUE TITLE
Problems with new dotdict syntax in JSON files

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#145]
Code:
```
"dTestDict"          : {"ddKeyA" : "ddKeyA_value", "ddKeyB" : "ddKeyB_value"},
"ddKeyB_param"       : ${params.global.dTestDict.ddKeyB}
```

Outcome:
The value of `ddKeyB_param` is `ddKeyB_value` (like expected)

I extend the above code with:

`${params}['global']['dTestDict']['ddKeyA'] : {"ddKeyA_2" : "ddKeyA_2_value"},`

Some more complicated tests fail:

Code:
`"ddKeyA_2_param_1" : ${params.global.dTestDict.ddKeyA.ddKeyA_2}`

Outcome:
`[ ERROR ] Loading of JSON configuration file failed! Reason: The variable 'params['global']['dTestDict']['ddKeyA']['ddKeyA_2']' is not available!`

Code:
`"ddKeyA_2_param_2" : ${params.global.dTestDict.ddKeyA}['ddKeyA_2'],`

Outcome:
`'Expecting property name enclosed in double quotes: line 35 column 26 (char 857)'`

Code:
`"ddKeyA_2_param_3" : ${params.global.dTestDict}['ddKeyA']['ddKeyA_2'],`

Outcome:
`'Expecting property name enclosed in double quotes: line 38 column 26 (char 941)'`

Code:
`"ddKeyA_2_param_4" : ${params.global}['dTestDict']['ddKeyA']['ddKeyA_2']`

Outcome:
`[ ERROR ] Loading of JSON configuration file failed! Reason: The variable 'params.global['dTestDict']['ddKeyA']['ddKeyA_2']' is not available!`

Did I made something wrong or is it not allowed to do it like above?

Issue maybe is related to
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/143

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your quick finding!
"""
Outcome:
The value of ddKeyB_param is ddKeyB_value (like expected)

I extend the above code with:

${params}['global']['dTestDict']['ddKeyA'] : {"ddKeyA_2" : "ddKeyA_2_value"},

Some more complicated tests fail:

Code:
"ddKeyA_2_param_1" : ${params.global.dTestDict.ddKeyA.ddKeyA_2}

Outcome:
[ ERROR ] Loading of JSON configuration file failed! Reason: The variable 'params['global']['dTestDict']['ddKeyA']['ddKeyA_2']' is not available!
"""
This issue was fixed in the latest commit, could you please help me check again.

For the case ""ddKeyA_2_param_2" : ${params.global.dTestDict.ddKeyA}['ddKeyA_2']", I was not aware of the way we mix dotdict format with traditional format in the same nested param. We will discuss more about this scenario in next sync up meeting.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

you're right. Also for me these combinations are new. I never thought about them. But now I do ;-)

I think we have a problem: unclear requirements! What shall be possible, what not? It seems to me that it is a hard challenge to implement a parser that is able to exchange even single values within composite data types. But either the preprocessing of JSON files works with all possible combinations of code inside, or a proper error message is mandatory in case of something has been found, that cannot be computed.

But currently the parser works in a way that makes it mostly impossible to debug in case of unexpected behavior. 

For example:

```
"dTestDict"          : {"ddKeyA" : "ddKeyA_value", "ddKeyB" : "ddKeyB_value"},
"ddKeyB_param"       : ${params.global.dTestDict.ddKeyB},
// ${params}['global']['dTestDict']['ddKeyA'] : {"ddKeyA_2" : "ddKeyA_2_value"}
```

The first line assigns a string value to key '`ddKeyA`' and a string value to key '`ddKeyB`' (as part of the test dictionary '`dTestDict`'). The second line uses the new dot notation to assign the value of key '`ddKeyB`' to a new string variable. In the robot file I log the parameter '`ddKeyB_param`' - and get the proper value ('`ddKeyB_value`').

Now I uncomment the third line, in which I overwrite the string value of key '`ddKeyA`' with a dictionary, containing one single key ('`ddKeyA_2`').

Executing the robot file now produces the following error:

`Variable '${ddKeyB_param}' not found`

Why this? I have a dictionary with two keys; and every key has an initial value. Now I overwrite the first key only. Then I would expect still to have the second key available with the same initial value. But in the example above the second key seems not to be available any more.

This is so much strange: It is not this assignment that causes the error

`"ddKeyB_param"       : ${params.global.dTestDict.ddKeyB},`

No, it's the logging of `${ddKeyB_param}` that fails. Why is this parameter not available if the assignment of a value to this parameter don't cause an error?

Oh dear!

My complete test code:

```
"dTestDict"          : {"ddKeyA" : "ddKeyA_value", "ddKeyB" : "ddKeyB_value"},
"ddKeyB_param"       : ${params.global.dTestDict.ddKeyB},
${params}['global']['dTestDict']['ddKeyA'] : {"ddKeyA_2" : "ddKeyA_2_value"}
// [ ERROR ] Loading of JSON configuration file failed! Reason: The variable 'params['global']['dTestDict']['ddKeyA']['ddKeyA_2']' is not available!
// "ddKeyA_2_param_1" : ${params.global.dTestDict.ddKeyA.ddKeyA_2},
// 'Expecting property name enclosed in double quotes: line 35 column 26 (char 857)'
// "ddKeyA_2_param_2" : ${params.global.dTestDict.ddKeyA}['ddKeyA_2'],
// 'Expecting property name enclosed in double quotes: line 38 column 26 (char 941)'
// "ddKeyA_2_param_3" : ${params.global.dTestDict}['ddKeyA']['ddKeyA_2'],
// [ ERROR ] Loading of JSON configuration file failed! Reason: The variable 'params.global['dTestDict']['ddKeyA']['ddKeyA_2']' is not available!
// "ddKeyA_2_param_4" : ${params.global}['dTestDict']['ddKeyA']['ddKeyA_2'],
```

**Comment by namsonx** [comment]
Hello Holger,

The issue you mentioned above was fixed in the pull-request 52 of JsonPreprocessor repository.

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and already merged.
