### ISSUE TITLE
Update of documentation and tutorial

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#146]
After clarification of:

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/142
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/143
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/145

(dotdict syntax and support of lists in JSON files)

the documentation and the tutorial should be extended by some examples.

(Task for @HolQue )

**Comment by HolQue** [comment]
Done for tutorial with:
https://github.com/test-fullautomation/robotframework-tutorial/pull/29

Main docu will follow after code stabilization (to avoid merge conflicts).

**Comment by HolQue** [comment]
Done also for component documentation:

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/185

Work finished.

**Comment by test-fullautomation** [comment]
solved and already merged with #185
