### ISSUE TITLE
test shall replace atest

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-testsuitesmanagement#150]
Hi Son,

please review the test cases provided by Holger.
Goal for 0.8.0 is that `test` replaces current tests in `atest` folder.

Please add missing tests in discussion with Hoger.

Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas, Hello Holger,

I looked into the list of TSM test cases which were design by Holger, the configuration level 3 is not covered.

Thank you,
Son

**Comment by HolQue** [comment]
Level 3 covered by:

TSM_0010
With parameter configuration file taken from config folder (placed beside the executed robot file); robot file has same name as configuration file
Expected: Configuration parameters taken from configuration file with same name as the robot file

TSM_0011
With parameter configuration file taken from config folder (placed beside the executed robot file); robot file has another name as configuration file
Expected: Configuration parameters taken from configuration file with predefined default name (robot_config.json)

TSM_0012
With parameter configuration file taken from config folder (placed beside the executed robot file); robot file has another name as configuration file; single parameter in command line (teststring_variant)
Expected: Configuration parameters taken from configuration file with predefined default name (robot_config.json); single command line parameter value overwrites variant 'robot_config' configuration value
Comment: Single file execution 

Test files:
test\testfiles\configfoldertests

**Comment by test-fullautomation** [comment]
Hi Son,
please confirm.
Thank you,
 Thomas

**Comment by namsonx** [comment]
> 

Hello Holger,

Sorry it's my mistake :)

Hello Thomas, Configuration level 3 is already covered in test cases TSM0010, TSM0011, TSM0012.

Thank you,
Son

**Comment by test-fullautomation** [comment]
O.K. Then I close this as done. Thank you!
