### ISSUE TITLE
Config.CConfig.dotdict shall be replaced by robot.utils.dotdict.DotDict

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-testsuitesmanagement#152]
Config.CConfig.dotdict shall be replaced by robot.utils.dotdict.DotDict

It is not useful to have two different docditct implementations running in Robot code.

**Comment by namsonx** [comment]
Hello Thomas,

I created the pull-request #160 for this ticket.

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and already merged with #160
