### ISSUE TITLE
Duplicated path definitions

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#163]
The path to JSON file is defined twice:

```
if not bLevel3Check:
    if os.path.isfile(self.sTestcasePath + 'config' + os.path.sep + 'robot_config.json'):
        self.sTestCfgFile = self.sTestcasePath + 'config' + os.path.sep + 'robot_config.json'
```

This causes code that is long winded and difficult to maintain.

Why not in this way:

```
if not bLevel3Check:
    self.sTestCfgFile = self.sTestcasePath + 'config' + os.path.sep + 'robot_config.json'
        if os.path.isfile(self.sTestCfgFile):
            ...
```

?

**Comment by HolQue** [comment]
To give all paths an unique look&feel (operating system independend!) you principally should use `"/"` instead of `os.path.sep`, because also under Windows we should not have backslashes in our paths.

**Comment by namsonx** [comment]
Hello Holger,

The code was updated, the block of code you mentioned in this ticket doesn't present in testsuitesmanagement repository.
Shall we close this ticket?

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Holger,
what is the status of this issue?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

partially improved, partially not. Difficult to decide what to do with this ticket. This code is part of the function loadCfg().

And the entire code of this function is confusing, long winded, unfavorable, not explained by code comments and therefore very difficult to understand.

The best would be to rework the entire code of this function completely. But if this is not in focus, you may close the ticket.

In my opinion it makes no sense to spend time again to make a code review and write down all issues.

**Comment by test-fullautomation** [comment]
Hi Holger,

we can make once the issues are solved a code maintenance ticket where we maintain the whole code.
I think that's the best.

Thank you,
 Thomas
