### ISSUE TITLE
Commented lines

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#164]
Some lines of code are commented out:

`#self.rConfigFiles.bLevel4 = True`

Please decide it they are still required. If not, please remove.

**Comment by namsonx** [comment]
All commented lines ```#self.rConfigFiles.bLevel4 = True``` are removed out of the code.

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
