### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#165]
```
            if not self.bConfigLoaded:
                #self.rConfigFiles.bLevel4 = True
                sDefaultConfig=str(pathlib.Path(__file__).parent.absolute() / "robot_config.json")
                self.sTestCfgFile = sDefaultConfig
else:
    self.rConfigFiles.bLevel3 = False
    if not self.bConfigLoaded:
        #self.rConfigFiles.bLevel4 = True
        sDefaultConfig=str(pathlib.Path(__file__).parent.absolute() / "robot_config.json")
        self.sTestCfgFile = sDefaultConfig
```

[1]
It seems to me that the intermediate variable `sDefaultConfig` is not really required.

[2]
The path to `sDefaultConfig` is defined several times. Why? The value is the same. Please try to avoid this. It's the default config file. And because of that you should initialize the path at the beginning of your code in this way:

`self.sTestCfgFile = str(pathlib.Path(__file__).parent.absolute() / "robot_config.json")`

If nothing else is defined by the user, this initial value is used, otherwise the value will be overwritten in the following code.

[3]
Like already mentioned in another issue: Things should be done in an unitary way. Therefore avoid to intermix different path computation mechanisms like `CString::NormalizePath` and `pathlib.Path` in your code.

**Comment by test-fullautomation** [comment]
Hi Son,
what is the status of this issue?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
