### ISSUE TITLE
Final steps before release 0.8.0

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#169]
- [x] Fix level3 computation
- [x] Introduce error message in case of both can be found: file.json and file.jsonp
- [x] Rename extension (.json -> .jsonp) also in
  %ROBOTPYTHONPATH%\Lib\site-packages\RobotFramework_TestsuitesManagement\Config\robot_config.json
  %ROBOTTESTPATH%\config\robot_config.json
  Adapt the code, referring to these files
- [x] Rename extension (.json -> .jsonp) in interface descriptions (Python code); main part in PDF docu is already adapted
- [x] Increase package version and version date
- [x] Update history with latest changes

**Comment by test-fullautomation** [comment]
Hi  Holger,
thank you for the summary!
Thomas
