### ISSUE TITLE
File MANIFEST.in outdated

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#178]
File MANIFEST.in contains outdated package name:

```
include RobotFramework_Testsuites/Config/robot_config.jsonp
include RobotFramework_Testsuites/Config/configuration_schema.json
```
This causes the following error message during setup.py execution:

```
reading manifest template 'MANIFEST.in'
warning: no files found matching 'RobotFramework_Testsuites\Config\robot_config.jsonp'
warning: no files found matching 'RobotFramework_Testsuites\Config\configuration_schema.json'
```

**Comment by test-fullautomation** [comment]
@namsonx : What is the status of this issue?

**Comment by namsonx** [comment]
Hello Thomas,

I made small change via [the commit 4a680599](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/commit/4a68059919155286806284e230971ed2b234d594) to stabi branch ([namsonx/task/stabi_branch](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/tree/namsonx/task/stabi_branch)) to fix this issue.

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and already merged.
