### ISSUE TITLE
Missing entries in history of documentation

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#181]
The current version of the testsuites management is 0.7.0 (packageversion.py). But the latest entry in history of the PDF documentation is 0.4.0

This causes a gap in the history that is not nice. In general I would prefer to have for every increased major number and also for every increased minor number (patch number not relevant enough) a corresponding entry in history. The history should give information about what happened in the software. If this is not aligned a history makes no sense. Please try to recover the corresponding milestones for missing entries 0.5.0, 0.6.0 and 0.7.0.

**Comment by test-fullautomation** [comment]
@namsonx : What is the status of this issue?

**Comment by namsonx** [comment]
Hello Holger,

I traced back the old commits and updated the history.

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
