### ISSUE TITLE
default config not found

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#186]
CConfig.py:

`sDefaultConfig=str(pathlib.Path(__file__).parent.absolute() / "robot_config.json")`

File has been renamed to robot_config.json in between.

**Comment by namsonx** [comment]
Hello Holger,

I already created the pull-request #177  (https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/177/files)
This pull request also merged to develop branch but I don't know why my change is disappearing?

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
maybe this got lost when the merge conflicts were resolved.
Please create as soon as possible new pull-request with a fix for this issue.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
fixed and already merged with #188

**Comment by namsonx** [comment]
Hello Thomas,

Thank you for helping me create the pull-request for this ticket.

Thank you,
Son

**Comment by test-fullautomation** [comment]
no problem...
