### ISSUE TITLE
Unfavorable configuration file search at level 3

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#192]
Possible JSON files to search for, are defined in this way:

```
sJsonFile1 = f"{sConfigFolder}/{sSuiteFileName.split('.')[0]}.jsonp"
sJsonFile2 = f"{sConfigFolder}/{sSuiteFileName.split('.')[0]}.json"
```

But in my opinion we cannot assume to get the full file name at index 0 in every case. Because this does not work in case of the file name contains further dots.

I tried:

```
tsm-cft-test.file-1.robot
config/tsm-cft-test.file-1.jsonp
config/robot_config.jsonp
```

Outcome:

`Parameters loaded from '..... config/robot_config.jsonp'`

But expected:

`Parameters loaded from '..... config/tsm-cft-test.file-1.jsonp'`

**Comment by HolQue** [comment]
`os.path.splitext()` solves the issue:

```
sJsonFile1 = f"{sConfigFolder}/{os.path.splitext(sSuiteFileName)[0]}.jsonp"
sJsonFile2 = f"{sConfigFolder}/{os.path.splitext(sSuiteFileName)[0]}.json"
```

**Comment by test-fullautomation** [comment]
@namsonx : What is the status of this issue?

**Comment by namsonx** [comment]
Hello Thomas,

I made small change via [the commit 0bc9cc4a](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/commit/0bc9cc4a10075ab3d392e41ab163f088b8c864f7) to stabi branch ([namsonx/task/stabi_branch](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/tree/namsonx/task/stabi_branch)) to fix this issue.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful

**Comment by test-fullautomation** [comment]
solved and already merged.
