### ISSUE TITLE
Error when deepcopy the variable(s) which is defined in json file(s) in robot testcase

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/robotframework-testsuitesmanagement#20]
An error `KeyError: '__deepcopy__'` occurs when deepcopy the variable which is defined in json configuration file.

Sample robot testcase to deepcopy an `__TESTBENCH__CONFIG` which defined in json file
```
*** Settings ***
Library     RobotFramework_Testsuites    WITH NAME    testsuites
Library     Collections
Suite Setup      testsuites.testsuite_setup    ../../../config/testsuites_config.json
Suite Teardown   testsuites.testsuite_teardown

*** Test Cases ***
Error when deepcopy a variable from json configuration file
    ${new_config}=     Copy Dictionary   ${__TESTBENCH__CONFIG}    deepcopy=True
```

I have investigated and found that the error comes from the **dotdit** module which is used in **testsuitesmanament**.
I observe that robotframework also has [dotdict module](https://github.com/test-fullautomation/robotframework/blob/develop/src/robot/utils/dotdict.py) which works properly as our expectation.

Thank you,
Ngoan

**Comment by namsonx** [comment]
Hello Ngoan,

    I have just checked, this is limited of deepcopy() method on dotdict object.
    I will try to find the solution to fix this issue.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Ngoan,

     I made the change regarding to this issue: Pull request #21 

Thank you,
Son

**Comment by test-fullautomation** [comment]
This issue is solved.
