### ISSUE TITLE
Documentation and readme have no link to tutorial

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-testsuitesmanagement#200]
The documentation and readme have no link to the tutorial.

Also how to open the html documents of the tutorial need to be documented:
e.g. 

> Here you find the rendered [Tutorial documentation](https://htmlpreview.github.io/?https://github.com/test-fullautomation/robotframework-tutorial/blob/develop/900_building_testsuites/building_testsuites.html).

**Comment by HolQue** [comment]
Should be solved by
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/203

**Comment by test-fullautomation** [comment]
solved an already merged with #203
