### ISSUE TITLE
Alignment of error messages wanted

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#209]
The self test of the Testsuites Management contains (beneath others) two BADCASE test cases (**TSM_0064** and **TSM_0252**), where variables are missing. The corresponding entries in Robot Framework log files are very different:

**TSM_0064-(VARIANT_HANDLING)-[BADCASE]**

```
UNKNOWN - Could not set variable 'params['global']['teststring_bench']' with value 'I am the 'bench1' configuration of tsm-test'! Reason: name 'params' is not defined
DEBUG - Could not set variable 'params['global']['teststring_bench']' with value 'I am the 'bench1' configuration of tsm-test'! Reason: name 'params' is not defined
```

**TSM_0252-(NESTED_CONFIG)-[BADCASE]**

```
ERROR - Loading of JSON configuration file failed! 
          Reason: Could not set variable 'params['global']['dTestDict']['I-am-not-existing']['I-am-not-existing']' with value 'Val_1'! Reason
                  I-am-not-existing'
```
**TSM_0064:**

* Hint regarding failed file load is missing
* Error message appears twice (with labels: UNKNOWN and DEBUG)

**TSM_0252:**

* The line break after the second "Reason" causes the name of the missing variable placed in a separate line, without any further information. That is unfavorable for the self test (that is based on a 'line by line' logfile comparison).
* In opposite to **TSM_0064** the error message is labelled with ERROR.

This should be aligned.

We do not need three different labels (UNKNOWN, DEBUG, ERROR) for error messages indicating a missing variable.

Expected is a common format of such error messages, like:

```
ERROR - Loading of JSON configuration file failed! 
          Reason: Could not set variable '...' with value '...'
          Reason: Variable '...' is not defined
```

Maybe completed by this addition:

`Aborting now. The test result will be UNKNOWN.`

**Comment by test-fullautomation** [comment]
@namsonx : What is the status of this issue?

**Comment by namsonx** [comment]
Hello Thomas,

This ticket was implemented.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
