### ISSUE TITLE
Implicit creation of data structures fail

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#214]
To test the implicit creation of data structures I introduced `TSM_1100`.

This test case uses `tsm-test_config_implicit_creation.jsonp`.
This file imports `tsm-test_config_implicit_creation.1.jsonp`.
And this file imports `tsm-test_config_implicit_creation.1.1.jsonp`.

In `tsm-test_config_implicit_creation.1.jsonp` a dictionary is created:

`"dTestDict" : {"kVal_1" : "Val_1"},`

In `tsm-test_config_implicit_creation.1.1.jsonp` this dictionary gets a second key, together with not yet existing sub keys:

`${params}['global']['dTestDict']['kVal_2']['I-am-not-existing']['I-am-not-existing'] : ${params}['global']['dTestDict']['kVal_1']`

But during test execution the dictionary `dTestDict` only contains one single key: `kVal_1`. The second key `kVal_2` is missing.
There is also no error message available in the log file indicating any problem with `kVal_2`.

I would expect that the dictionary `dTestDict` contains both keys.

**Comment by HolQue** [comment]
Hi Son,

I added the same test to the JsonPreprocessor

(https://github.com/test-fullautomation/python-jsonpreprocessor/pull/140)

This test is successful.

Seems that the root cause of this issue is inside the TestsuitesManagement, and not inside the JsonPreprocessor.

**Comment by namsonx** [comment]
Hello Holger,

After debugging carefully, I found the cause in the JsonPreprocessor.
I created [the new commit](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/7c1352a202813fc8968c13b8e223a19bbed8d108) on stabi branch to fix this issue.
Could you please verify test case ID TSM_1100 again?

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

TSM_1100 works now! But I have to adapt the reference log file. Pull request soon.

Nevertheless, there is one aspect left that astonishes me. Like mentioned above, the same test case implemented in self test of JsonPreprocessor directly, was already successful yesterday. Why? If the error is in the JsonPreprocessor and not in the Testsuites Management, I would not expect this. What is the difference here? Maybe tomorrow in team meeting we can have a short discussion about that.

**Comment by HolQue** [comment]
Hi Son,

correction: The results are like expected, but while taking a look at the log file, I observe the following error message:

`Could not convert: CConfig.ddictJson.kVal_2.I-am-not-existing = DotDict({'I-am-not-existing': 'Val_1'}) to dotdict`

Is there still a problem?

**Comment by namsonx** [comment]
Hello Holger,

When implemented dotdict feature in the TestsuitesManagement package, a dict which could not convert to dotdict format will be kept as current dict format and raise a log output.
```
  if isinstance(item, dict):
      self.lTmpParam.append(k+"["+str(n)+"]")
      for i in self.lTmpParam:
          sExec = i if i == self.lTmpParam[0] else sExec + "." + i
      sExec = sExec + " = DotDict(" + str(item) + ")"
      try:
          exec(sExec, globals())
      except:
          logger.info(f"Could not convert: {sExec} to dotdict")
          pass
```
I already discussed this solution with Thomas when implementing it.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

OK, I understand that there is a possible problem, that requires an error handling. But I still have doubts.

The error message itself is completely confusing. No one will understand this. Why is the conversion not possible? What is the problem? What is the impact? We should try to give a little bit more guidance to the users.

In all tests I use my `PrettyPrint` function to log values I want to check. This function also prints the data type of all variables. The output of TSM_1100 is:

```
({dTestDict} / tsm-testfile-22-implicit_creation) : [DOTDICT] (2/1) > {kVal_1} [STR]  :  'Val_1'
({dTestDict} / tsm-testfile-22-implicit_creation) : [DOTDICT] (2/2) > {kVal_2} [DOTDICT] (1/1) > {I-am-not-existing} [DOTDICT] (1/1) > {I-am-not-existing} [STR]  :  'Val_1'
```
It can be seen: At every level in the composite data structure the data type is `dotdict`, and not `dict`.

This looks like a conversion to `dotdict` was possible.

Therefore I still do not understand the meaning of the error message in this case.

**Comment by namsonx** [comment]
Hello Holger, 

The purpose of this message info is to inform users that they have to use traditional dict format instead of dotdict in the test script in this case.
May be we should revise the message to avoid confusion in this situation.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son, hi Thomas,

* Does the Robot Framework give users the possibility to decide if they want to have a `dict` or a `dotdict`? Unclear to me. In my opinion we need a use case to clarify this situation. Again I ask for the impact! Either there is no impact, then we should remove this error message (or make it more common), or there is an impact, then this has to be explained in detail either in main documentation or in tutorial.

* My second question is still open: Why are all dictionaries of type `dotdict`, even in case of the error message tells me that a conversion to `dotdict` is not possible?

**Comment by test-fullautomation** [comment]
Hi both
my expectation would be that we use only dotdict. No need to use a "simple" dict.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Son,

this code:

```
except:
          logger.info(f"Could not convert: {sExec} to dotdict")
```
makes no sense in my opinion. Because you completely ignore the concrete root cause of the exception. And `sExec` is a value assignment, and not only a `dotdict` conversion. There are much more possible root causes for exceptions than failed `dotdict` conversions.

I extended the code in the following way:

```
except Exception as error:
    logger.info(f"Could not convert: {sExec} to dotdict. Exception: {error}")
```

Outcome:

`Could not convert: CConfig.ddictJson.kVal_2.I-am-not-existing = DotDict({'I-am-not-existing': 'Val_1'}) to dotdict. Exception: invalid syntax (<string>, line 1)
`

OK, a syntax issue! Not necessarily a `dotdict` issue.

Hmm, there is an expression with dots inside on the left hand side of the colon. These dots have a syntactical meaning. Is it ensured that the entire data structure already exists?

This code needs to be reviewed and improved.

**Comment by test-fullautomation** [comment]
Hi Son,
as per our discussion: please log the exact error, there it is at least visible, that there is no dotdict, but instead a syntax error.
Second: Holgers proposal to check the existence of objects inside the loop is a good improvement. It helps to give useful error messages.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I created new commit [e77b25a660](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/232/commits/e77b25a660193a1b9c941cf72ae2d6e8e7f6b5f2) to raise an error when converts configuration object to dotdict format failed.

Hello @HolQue , in the configuration file I observe you defined a key name "I-am-not-existing" that the reason builtin Docdict() function doesn't work because "-" is not allowed in key name.  

Thank you,
Son

**Comment by test-fullautomation** [comment]
Son waits for retest from Holger.

**Comment by HolQue** [comment]
Hi @namsonx , hi @test-fullautomation ,

there are some things I still have doubts.

I tried this:

```
"params" : {
   "global" : {
      ${params.global.level_1.level_2.level_3.level_4} : "levelvalue",
```

To see hat happen, I added some debug output (`logger.error`) to `CConfig.py`:

```
for k,v in oJson.items():
    sExec = ""
    if isinstance(v, dict):
        self.lTmpParam.append(k)
        for i in self.lTmpParam:
            sExec = i if i==self.lTmpParam[0] else sExec + "." + i
            logger.error(f"============= (dict) sExec: {sExec}")
        sExec = sExec + " = DotDict(" + str(v) + ")"
        logger.error(f"============= [final] (dict) sExec: {sExec}")
        try:
            exec(sExec, globals())
        except Exception as error:
            logger.error(f"Could not convert: {sExec} to dotdict.\nException: {error}")
            BuiltIn().unknown("Convert configuration object to dotdict format failed!!!")
```

This is the outcome:

```
ERROR - ============= (dict) sExec: CConfig.ddictJson
ERROR - ============= (dict) sExec: CConfig.ddictJson.level_2
ERROR - ============= [final] (dict) sExec: CConfig.ddictJson.level_2 = DotDict({'level_3': {'level_4': 'levelvalue'}})
ERROR - ============= (dict) sExec: CConfig.ddictJson
ERROR - ============= (dict) sExec: CConfig.ddictJson.level_2
ERROR - ============= (dict) sExec: CConfig.ddictJson.level_2.level_3
ERROR - ============= [final] (dict) sExec: CConfig.ddictJson.level_2.level_3 = DotDict({'level_4': 'levelvalue'})
```

I wonder why `CConfig.ddictJson` starts with level_2 (`CConfig.ddictJson.level_2`). Where is level_1?

I would expect that the loop starts with:

`[final] (dict) sExec: CConfig.ddictJson.level_1 = DotDict({'level_2': {'level_3': {'level_4': 'levelvalue'}}})`

Nevertheless: level_1 is existing and can be accessed during test:

`INFO - ${level_1} = {'level_2': {'level_3': {'level_4': 'levelvalue'}}}`

OK so far.

But with

`exec(sExec, globals())`

an assignment is executed. And the dotdict conversion is only a part of the entire executed expression. I already mentioned that there are more root causes for exceptions possible than the dotdict conversion only.

Therefore in

`logger.error(f"Could not convert: {sExec} to dotdict.\nException: {error}")`

you make an assumption (`Could not convert`) that can be wrong. You should remove this. "`Exception: {error}`" is enough.

I changed the code to (using '-' now):

`${params.global.level-1.level-2.level-3.level-4} : "levelvalue",`

Result:

```
ERROR - Could not convert: CConfig.ddictJson.level-2 = DotDict({'level-3': {'level-4': 'levelvalue'}}) to dotdict.
Exception: cannot assign to operator (<string>, line 1)
INFO - Could not convert JSON config to dotdict!!!
```

Now we see the real problem. Your statement is: "`Could not convert`". But the concrete reason for the exception is: "`cannot assign to operator`".

In log file we have the expected output:
`
INFO - ${level-1} = {'level-2': {'level-3': {'level-4': 'levelvalue'}}}`

This means: There are no problems with the dotdict conversion. And there are also no problems with the '-' inside key names.

So, what is the problem here? Unclear to me.

Finally the observation is: Even in case of such an exception "`cannot assign to operator`", the test is executed and the values are like expected.

Seems that things are not really aligned properly in the code. And no one wants to read such an error message in a log file of a passed test. I urgently ask you to review and rework your code.

**Comment by HolQue** [comment]
Now I see the difference:

with level_1 notation it's a dotdict, and `${level_1.level_2}` is possible inside robot files.

With level-1 notation it's a simple dict, and `${level_1.level_2}` is not possible inside robot files, but `${level-1}[level-2]`.

The failed dotdict conversion does not mean that the values are not available, they only have another data type.

This means also that '-' inside parameter or key names are not really forbidden.

So much tricky.

**Any recommendations for users?**

**Comment by test-fullautomation** [comment]
Hi Holger,
as written some days ago:
We should not allow hyphen  `-` as part of a parameter name. Variable name syntax shall follow python syntax.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger,

For the log message ```INFO - Could not convert JSON config to dotdict!!!```, this is my mistake due to I forgot remove error handling in the code below:
```
        bDotdict = False
        dotdictObj = CConfig.CJsonDotDict()
        try:
            jsonDotdict = dotdictObj.dotdictConvert(oJsonCfgData)
            bDotdict = True
        except:
            logger.info("Could not convert JSON config to dotdict!!!")
            pass
        del dotdictObj
```
This try catch must be removed caused the error handling is already handled inside ```dotdictConvert()```, and we decided to raise an error if configuration object could not convert to dotdict format.
I will update and push new commit to stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Thomas,

OK. My expectation now is:

* Add this rule to naming convention check (incl. corresponding error message: naming convention violation).
* Abort test with result UNKNOWN.
* Reduce the current error message (like described above).
* Check the root cause for error message "`Exception: cannot assign to operator (<string>, line 1)`" (still indicates a problem?).

**Comment by namsonx** [comment]
Hello Holger,

The root cause for error message "```Exception: cannot assign to operator (<string>, line 1)```"  in this case comes from the ```sExec``` statement ```CConfig.ddictJson.level-2 = DotDict({'level-3': {'level-4': 'levelvalue'}})```.
The ```CConfig.ddictJson.level-2``` in ```sExec``` is known as ```CConfig.ddictJson.level``` minus ```2``` by Python program, and that the reason we observe this error message.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

oh, now I understand (took some time ;-).

Now the situation is:

By mistake I use the forbidden '-' character in key names.

I get corresponding error messages:

```
[ ERROR ] Could not convert: CConfig.ddictJson.level-2 = DotDict({'level-3': {'level-4': 'levelvalue'}}) to dotdict.
Exception: cannot assign to operator (<string>, line 1)
```

This is plausible and fine to me now.

**But as long as I do not use the affected names in robot code, the test is executed and can also be passed.**

I would prefer to have a hard cut here, with the test execution aborted. We should not allow a test being executed with a configuration, that contains invalid names.

And the error messages are rather technical - and therefore confusing for not so much experienced users.

Maybe it's possible to find a more smooth wording, e.g. something like:

`Exception occurred while parsing the test configuration. Please check your configuration files for invalid identifiers. The computation will be aborted now.
`

Later, when a full naming convention check is available, then this check may provide a more detailed error message.

**Comment by test-fullautomation** [comment]
Hi Holger,
what is the status of this issue?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

we still do not have a naming convention check that would prevent us from running into problems like described in this issue.

We still have open questions:
https://github.com/test-fullautomation/python-jsonpreprocessor/issues/157#issuecomment-1907774471

And code like

`${params.global.level-1.level-2.level-3.level-4} : "levelvalue",`

still causes strange errors like

```
[ ERROR ] Could not convert: CConfig.ddictJson.level-2 = DotDict({'level-3': {'level-4': 'levelvalue'}}) to dotdict.
Exception: cannot assign to operator (<string>, line 1)
```

with test is executed and PASSED!

I do not know what to do with this issue.

**Comment by HolQue** [comment]
Retest mostly successful.

Code like

${params.global.level-1.level-2.level-3.level-4} : "levelvalue",

works now.

Still open aspects (like naming convention checks) are already covered by other issues and should be tracked there. Therefore I suggest to close this issue.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
