### ISSUE TITLE
Code maintenance (1)

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#216]
**[1]**

The file

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/blob/develop/RobotFramework_TestsuitesManagement/Config/CConfig.py

contains:

```
if self.sTestCfgFile != '':
    self.sTestCfgFile = CString.NormalizePath(self.sTestCfgFile)
```

Please be aware of: If `NormalizePath` gets an empty string, `NormalizePath` returns an empty string.
Additionally `NormalizePath` also removes trailing and leading spaces.

To check if `self.sTestCfgFile != '':`, is not necessary. This can be removed.

**[2]**

The file also contains:

```
if self.sLocalConfig != '':
    try:
        oLocalConfig = oJsonPreprocessor.jsonLoad(CString.NormalizePath(self.sLocalConfig))
```

In general such way of handling things makes me worried.

A variable shall be checked before usage. OK. But before you use the variable, you modify the value (with `NormalizePath`).
Outcome: You do not work with what you have checked. You work with something different.

In the example above this might not be critical. But nevertheless, in my opinion this is dangerous and should be avoided.

I would prefer the following version:

```
self.sLocalConfig = CString.NormalizePath(self.sLocalConfig)
if self.sLocalConfig != '':
    try:
        oLocalConfig = oJsonPreprocessor.jsonLoad(self.sLocalConfig)
```

**Comment by namsonx** [comment]
Hello Holger,

Thank you for the hints! I updated via [commit ea42a56e3](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/commit/ea42a56e3a8506cbbd2c238e2b0f14985573c221) on stabi branch.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Holger,
is this issue retested?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

code is improved like described.
