### ISSUE TITLE
Parameter substitution does not work properly

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#223]
The goal behind this use case is to use the `${}` substitution mechanism to add suffixes to a string (several cumulating suffixes in several separate steps = separate lines in JSON file).

Within

```
   "params" : {
      "global" : {
```
the test string is initialized in this way:

`"teststring" : "teststring.value"`

in robot test case the value is logged:

`"teststring.value"`

I extend the code:

```
"teststring" : "teststring.value",
${params.global.teststring} : "${params.global.teststring}.suffix-1"
```

And the value is

`"teststring.value.suffix-1"`

(like expected)

Again I extend the code:

```
"teststring" : "teststring.value",
${params.global.teststring} : "${params.global.teststring}.suffix-1",
${params.global.teststring} : "${params.global.teststring}.suffix-2"
```

And the value is

`"teststring.value.suffix-2"`

This is not expected. Expected is

`"teststring.value.suffix-1.suffix-2"`

**Comment by test-fullautomation** [comment]
Hi Son,
this is a showstopper for 0.9.0. So please work with priority on this issue.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger,

The root cause of this issue came from Jsonpreprocessor package, I had pushed the fix to [python-jsonpreprocessor (stabi branch)](https://github.com/test-fullautomation/python-jsonpreprocessor/tree/namsonx/task/stabi_branch).

Thank you,
Son

**Comment by test-fullautomation** [comment]
Son waits for retest from Holger.

**Comment by HolQue** [comment]
Retest successful (TSM_1200).

Issue can be closed.

**Comment by lxndrttz** [comment]
Still face a similar issue with this example:

```
{
   "params" : {
      "global" : {

         // works for plain parameters ...
         "plainparameter" : "root",
         ${params.global.plainparameter} : "${params.global.plainparameter}.level1",
         ${params.global.plainparameter} : "${params.global.plainparameter}.level2",
         ${params.global.plainparameter} : "${params.global.plainparameter}.level3",

         // but fails for parameter structures, e.g.
         "testbench" : {
            "config" : {
               "filepath" : "root"
            }
         },
         ${params.global.testbench.config.filepath} : "${params.global.testbench.config.filepath}.level1",
         ${params.global.testbench.config.filepath} : "${params.global.testbench.config.filepath}.level2",
         ${params.global.testbench.config.filepath} : "${params.global.testbench.config.filepath}.level3"
      }
   }
}
```


Outputs:

`plainparameter = "root.level1.level2.level3"`  as expected.
`testbench.config.filepath = "root.level3"`  which is not expected (expected: "root.level1.level2.level3").

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
please look into this use-case.
@HolQue , can you please create a test case for this example, too.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Already done

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/234

:-)

**Comment by test-fullautomation** [comment]
@lxndrttz : Which RobotFramework AIO version was this?

**Comment by test-fullautomation** [comment]
@HolQue : please provide also a pull-request.

**Comment by HolQue** [comment]
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/234

**Comment by lxndrttz** [comment]
Issue was observed using version 0.9.2.0 for Windows.

**Comment by namsonx** [comment]
Hello Thomas, Hello Holger,

I fixed this issue and have just pushed new commit [45cb44b81](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/45cb44b8147bb280b77db0fcc4aa1c010d983d76) to JsonPreprocessor's stabi branch.

The new test case JPP_0510 is also passed.

Hello @lxndrttz, thank you very much for your finding!

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
can you please provide a pull-request for the current stabi branch.
Alexander would like to experiment with this fix based on our daily build.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I created [new pull-request](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/171) from stabi branch to develop branch.

Thank you,
Son
