### ISSUE TITLE
Test execution freezes

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#225]
The JSON code

```
"params" : {
   "global" : {
               "teststring" : "eins",
               "teststring" : "${params.global.teststring}.zwei"
   }
}
```
makes the Robot Framework freeze (before start of test execution).

Maybe an endless loop?

**Comment by namsonx** [comment]
Hello Holger,

This is very interesting scenario, the parameter ```teststring``` is defined and then ```teststring``` is redefined right below at the same level of Json configuration file.
When loading this JSON file, method ```json.loads()``` of json package will ignore the first ```teststring``` and take the second ```teststring```. And now, the ```teststring``` is set by value of ```${params.global.teststring}``` while the ```teststring``` was not defined yet in this case. That the reason JsonPreprocessor package jump to the endless loop.
I will fix this endless loop issue.
Now, the question is: Do we allow this scenario? or we should raise error message in this case?

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

for me the code looks plausible and should be allowed.

**Comment by test-fullautomation** [comment]
Hi Son,
my expectation would be that the code is processed from top to bottom.
Therefore when "zwei" is created, then params.global.teststring is already existing with value "eins". I would expect that setting the new value "zwei" is possible this way, too.
Thank you,
 Thomas

**Comment by HolQue** [comment]
New value to be expected "eins.zwei".

**Comment by test-fullautomation** [comment]
Hi Son,
this is a showstopper for 0.9.0. So please work with priority on this issue.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas, Hello Holger,

I had analyzed this issue and the root cause comes from JsonPreprocessor package.
I fixed this issue and created [new pull-request](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/159) on JsonPreprocessor repository.

Thank you,
Son

**Comment by HolQue** [comment]
Issue solved with

https://github.com/test-fullautomation/python-jsonpreprocessor/pull/159
