### ISSUE TITLE
TSM_0064 failed

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#242]
With latest changes in JsonPreprocessor the self test case **TSM_0064** fails.

**TSM_0064** is a BADCASE test of variant handling: A local config file is passed to command line parameter config_file.

Because of a local config file is not a full configuration file, this error occurred previously:

`UNKNOWN - Could not set variable 'params['global']['teststring_bench']' with value 'I am the 'bench1' configuration of tsm-test'! Reason: name 'params' is not defined`

This error is changed now to:

`UNKNOWN - Exception occurred.`

I would prefer to have the previous error message back.

**Comment by namsonx** [comment]
Hello Holger,

The error message from JsonPreprocessor (JPP) is changed in this case because our new requirement:
•	In JPP [ticket 182](https://github.com/test-fullautomation/python-jsonpreprocessor/issues/182):
-	We decided to set root key in case it’s not available
 ```
Hi Thomas, hi Son,

while updating the documentation I continued with playing around with possibilities. Outcome: Several issues need to be fixed:

(1)
${testdict.subKey.subKey.paramA} : "DEF" 
returns: Could not set variable ... Reason: name 'testdict' is not defined'

NOT OK
```
-	It means now if JPP loads a jsonp file like the file "config_file: ./localconfig/tsm-test_localconfig_bench1.jsonp" in TSM_0064 which contains:
```
{
   ${params}['global']['teststring_bench'] : "I am the 'bench1' configuration of tsm-test"
}
```
-	Now, JPP does not raise error message “Could not set variable ... Reason: name 'params' is not defined'” any more, instead the TestsuitesManagement package will raise the error message that the required property is not in configuration file:
```
[ ERROR ] The parameter 'Project' is a required property in configuration file C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\robotframework-testsuitesmanagement\test\testfiles\localconfig\tsm-test_localconfig_bench1.jsonp.
```
In this case I think we should update the verified log message in selftest.

Thank you,
Son

**Comment by HolQue** [comment]
The error I get is:

`UNKNOWN - Exception occurred.`

**Comment by namsonx** [comment]
Hello Holger,

I just run and get error message at the top of test suite like below:
```
C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\robotframework-testsuitesmanagement\test\testfiles>%RobotPythonPath%\python -m robot.run --variable config_file:"C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\robotframework-testsuitesmanagement\test\testfiles\localconfig\tsm-test_localconfig_bench1.jsonp" tsm-testfile-01.robot
==============================================================================
Tsm-Testfile-01
==============================================================================
[ ERROR ] The parameter 'Project' is a required property in configuration file C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\robotframework-testsuitesmanagement\test\testfiles\localconfig\tsm-test_localconfig_bench1.jsonp.

Test Case tsm-testfile-01 :: tsm-testfile-01                          | UNKNOWN |
Parent suite setup unknown:
Exception occurred.
------------------------------------------------------------------------------
Tsm-Testfile-01                                                       | UNKNOWN |
Suite setup unknown:
Exception occurred.

1 test, 0 passed, 0 failed, 1 unknown
==============================================================================
Output:  C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\robotframework-testsuitesmanagement\test\testfiles\output.xml
Log:     C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\robotframework-testsuitesmanagement\test\testfiles\log.html
Report:  C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\robotframework-testsuitesmanagement\test\testfiles\report.html

C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\robotframework-testsuitesmanagement\test\testfiles>
```

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

what you list above, is the console output. But the self test is based on a comparison of the log files. And in the log file the error message is not seen.

What have you done to reproduce the error I described? In your console listing I miss the debug output file. Therefore this cannot be a TSM self test result. Have you executed TSM_0064? Or have you executed the affected robot file manually? This would make no sense! You have to execute TSM_0064. Then you would have a debug log file. And this file only contains

`UNKNOWN - Exception occurred.`

and not your detailed error message.

For me the question is: Why is this message not logged?

**Comment by HolQue** [comment]
OK, this is the error message:

`[ ERROR ] The parameter 'Project' is a required property in configuration file C:\...\tsm-test_localconfig_bench1.jsonp.`

And is this the code, that causes this error message?

`logger.error(f"The parameter {error.message} in configuration file {self.sTestCfgFile}.\n")`

Hmm, this way of combining strings with parameters to generate an error message, is really interesting ;-)

Please add single quotes around `{self.sTestCfgFile}`.

**Comment by namsonx** [comment]
Hello Holger,

I updated the error message log as your comment, and added into the pull-request from stabi branch to develop branch.

Thank you,
Son

**Comment by HolQue** [comment]
I am still confused. Already in

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/83

I analyzed the logging functions and I wrote:

`Because logger.error(<error message>) does not write the error message into the text log file (-b command line option) - but BuiltIn().unknown(<error message>) does. `

And this seems to be the problem, because the error message I miss in the log file, is written by `logger.error` and therefore cannot be present in log file.

But previously the self test works. So what is the problem now? What has been changed in between in the code? I have no idea what is going on here and still further investigation is required.

**Comment by namsonx** [comment]
Hello Holger,

```logger.error``` is error log mechanism of Robot Framework.
Previously, we can observe error message in the text log file because the error message came form ```raise Exception(<error message>)``` in JsonPreprocessor package.
Now, due to the requirement changed, the jsonp file in the TSM_0064's test scenario do not cause any ```Exception```. Then instead of exception from JPP, the error massage is raised by ```logger.error``` from Robot test suite.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

OK, clear to me now. But the problem still is:

Instead of a speaking error message we have an "`UNKNOWN - Exception occurred.`" in the log file. And this does not help anyone.

We need a speaking error message for at least two reasons:
* Users need to be informed
* An automated self test needs to be supported

All like before!

What do you plan now to solve the problem?

**Comment by namsonx** [comment]
Hello Holger,

For this, we have to modify Robot Framework core to to update error message to ```UNKNOWN-<error-massge>``` state instead of ```UNKNOWN - Exception occurred.```.
Cuong will handle this implementation :)

Thank you,
Son

**Comment by test-fullautomation** [comment]
@milanac030988 : Can you please look into this issue?
@HolQue : in this case we need to adapt as intermediate solution the testcase to the new error-message.

**Comment by HolQue** [comment]
Hi @milanac030988

before you start please take a look at my proposal at the end of

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/83#issue-1532185345

**Comment by HolQue** [comment]
I already adapted the error message to the new official one. But intermediately I will change this to

`Exception occurred.`

Update of pull request soon.

**Comment by HolQue** [comment]
Hi Son,

I still try to understand, but I fail. We can discuss directly at Monday.

For now only some observations:

**CConfig.py**

nearby

`if bJsonSchema:`

I see line

`BuiltIn().unknown('JSON schema validation failed!')`

But I can see this message neither in console nor in debug log file. Why this? Or asked other way round: What do I have to do to see this message anywhere in log or console?

I added an own message

```
if bJsonSchema:
    BuiltIn().log(f">>>>>>>>>>>> test output:")
```

Same result: not logged.

I tried:

```
if bJsonSchema:
    BuiltIn().log(f">>>>>>>>>>>> test output:", "ERROR")

```
Now the message is visible in console (because of trace level "ERROR"), but still not in debug log file.

I exchanged

`logger.error(f"The parameter {error.message} in configuration file '{self.sTestCfgFile}'.\n")`

by

`BuiltIn().log(f"(--2--) The parameter {error.message} in configuration file '{self.sTestCfgFile}'.\n", "ERROR")`

Same outcome: visible in console, but not in debug log file.

You use `logger.info()` at some positions. I also added an own logger.info

`logger.info(f">>>>>>>>>>>> logger.info test output")`

at the beginning of `loadCfg()`.

Same result: Not seen anywhere.

I am really confused now, because this is in opposite to all what I experienced while I reworked the logging some weeks ago. Every `BuiltIn().log(..)` has been logged to debug log file. Why not here?

I switched to **CSetup.py** where `loadCfg(...)` is executed, and added

`BuiltIn().log(f">>>>>>>>>>>> test message")`

at the beginning of `testsuite_setup()`

Outcome: Test message not seen in console (OK, because trace level is default "INFO", and this level is not printed to console), **but is written now to debug log file!**

After this I added

`logger.info(f">>>>>>>>>>>> logger.info test output 2")`

**Also this info is written to debug log file.**

This is really interesting. Why do `BuiltIn().log()` and `logger.info()` work like expected at this position, but not inside `loadCfg(...)`? What is the difference?

In **CSetup.py** I also see this:

```
if not RobotFramework_TestsuitesManagement.CTestsuitesCfg.oConfig.bLoadedCfg:
    BuiltIn().unknown(CConfig.sLoadedCfgError)
    return
```

I extended to

```
if not RobotFramework_TestsuitesManagement.CTestsuitesCfg.oConfig.bLoadedCfg:
    BuiltIn().log(f">>>>>>>>>>>> bLoadedCfg: {RobotFramework_TestsuitesManagement.CTestsuitesCfg.oConfig.bLoadedCfg}")
    BuiltIn().unknown(CConfig.sLoadedCfgError)
    BuiltIn().log(f">>>>>>>>>>>> test message after unknown")
    return
```

And the debug log file tells me:

```
INFO - >>>>>>>>>>>> bLoadedCfg: False
UNKNOWN - Exception occurred.
```

Very good: `BuiltIn().log()` works; the `bLoadedCfg` INFO is logged.

Now I want to see the error message and tried:

```
if not RobotFramework_TestsuitesManagement.CTestsuitesCfg.oConfig.bLoadedCfg:
    BuiltIn().log(f">>>>>>>>>>>> bLoadedCfg: {RobotFramework_TestsuitesManagement.CTestsuitesCfg.oConfig.bLoadedCfg}")
    BuiltIn().log(f">>>>>>>>>>>> sLoadedCfgError: '{CConfig.sLoadedCfgError}'")
    BuiltIn().unknown(CConfig.sLoadedCfgError)
    BuiltIn().log(f">>>>>>>>>>>> test message after unknown")
    return
```

But unfortunately the debug log file tells me:

`INFO - >>>>>>>>>>>> sLoadedCfgError: ''`

Hmm, nothing inside `CConfig.sLoadedCfgError`? Why not? Where is the error message gone?

I tried with an own error message, to verify what `BuiltIn().unknown()` is able to do at this position:

```
if not RobotFramework_TestsuitesManagement.CTestsuitesCfg.oConfig.bLoadedCfg:
    BuiltIn().log(f">>>>>>>>>>>> bLoadedCfg: {RobotFramework_TestsuitesManagement.CTestsuitesCfg.oConfig.bLoadedCfg}")
    BuiltIn().log(f">>>>>>>>>>>> sLoadedCfgError: '{CConfig.sLoadedCfgError}'")
    # BuiltIn().unknown(CConfig.sLoadedCfgError)
    BuiltIn().unknown("This is my own error message")
    BuiltIn().log(f">>>>>>>>>>>> test message after unknown")
    return
```

_Outcome: A BIG HOORAYY!!_

**My own error message is seen in console and in debug log file:**

`UNKNOWN - This is my own error message`

Conclusions:

* I admit, I do not really have much knowledge of the code. But I am very worried about my observations.
* Intuitively I would expect that is should be possible to log a message and then react on what happened (e.g. set the rest result to UNKNOWN). I cannot beliefe that it would be required to change the code of the RobotFramework core to enable this.
* I would assume now, that it is possible to solve the log problem easily e.g. by returning a non empty `sLoadedCfgError` inside `testsuite_setup` and log this with
  `BuiltIn().unknown(CConfig.sLoadedCfgError)`
  But still the question is why it is not possible to do this inside `loadCfg` directly.

**Comment by namsonx** [comment]
Hello Holger,

I pushed new commit [c137516797](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/239/commits/c1375167975de5db33c5c5a1d5816bf6ccaae8a5) to the stabi branch to fix the issue based on test case TSM_0064.

Could you please help me update log template again for TSM_0064?

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

**TSM_0064** works now!

But your code change has an impact on further self test cases, e.g. **TSM_0050**.

Previous error version:

```
ERROR - The parameter 'WelcomeString' is a required property in configuration file ...
UNKNOWN - JSON schema validation failed!
```

Actual error version:

```
ERROR - The parameter 'WelcomeString' is a required property in configuration file ...
FAIL - KeyError: 'WelcomeString'
```

In my opinion the first error version is the better one. Because the first line tells about what exactly went wrong. And the second line tells about the impact (the failed validation). To know about the impact is helpful for users.

Whereas in second error version the second line "`FAIL - KeyError: 'WelcomeString'`" is not really helpful for users. It's also mainly redundant to the first line.

I would prefer to have the first version back. Maybe in one line only.

Next aspect:

The fact that a parameter is required, is **not** the error. The error is that a required parameter is **missing**. The first line in error message is a bit incomplete.

Summarized, my proposal is:

`Error: Required parameter '...' is missing in configuration file '...'. JSON schema validation failed!`

Finally:

The test result is `FAIL` now, but expected is: `UNKNOWN` (like before).

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your quick feedback!
By mistake, I deleted the line of code that raise Unknown state, I added it again and updated the error message log as your suggestion in latest commit on stabi branch.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi  @namsonx ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

This was fixed, and run success on Gitlab.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
