### ISSUE TITLE
Missing error message in case of configuration issue

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#247]
This is the test content of a parameter configuration file of the TestsuitesManagement:

```
"params" : {
            "global": {
                         "testparam" : "paramvalue",
```

In case of I make the top level `"params"` invalid by

`"paramsZZZ" : {`

I get a schema validation error (like expected).

But if I make the level below invalid by

```
"params" : {
            "globalZZZ": {
```

Then I get this error: `Variable '${testparam}' not found.`

And this is plausible because during test execution the variable `testparam` is used.

But what makes me worried is that I do not get a schema validation error telling me that `"global"` is missing.

Because "params/global" variables are referred by

`${testparam}`

in tests, and not by

`${params}['global']['testparam']`

And this means that `"global"` is mandatory. The user is not free to use any other key name at this position in configuration file.

If `"global"` is missing I would prefer to have a corresponding error message. Test execution should end with `UNKNOWN` in this case.

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding! 
I implemented this ticket and pushed the change [41cde40ae7df2](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/commit/41cde40ae7df2dda77fbb2db1f92ca82ec0010ae) to stabi branch.

Could you please help me verify again!

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

now the error message is:

`Required parameter 'global' is missing in 'params' property in file ...`

We should avoid this additional term '`property`'. What is a _property_ in this context?

Maybe this can be an alternative:

`Required parameter 'global' is missing under 'params' in file ...`

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your suggestion! I updated on stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
