### ISSUE TITLE
History comment

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#250]
Latest addition in history:

`- Simplify local configuration loading based on the new version of JsonPreprocessor`

(1)
This is only one single sentence, not an itemization. Therefore we do not need the '-' at the beginning.

(2)
Use the past: 'Simplified'. 'Simplify' is imperative.

(3)
No need to mention the JsonPreprocessor in history of TestsuitesManagement. I dont't believe that anyone knows what to do with this piece of information.
Users of TestsuitesManagement do not necessarily know also about the JsonPreprocessor and about updates of this component.

(4)
Ok, something has been simplified. Is there any impact on the users? If not, it makes no sense to mention this in history.

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding, I updated the history comment!

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
