### ISSUE TITLE
Dictionary assignment by reference does not work

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#252]
The following JSON code

* defines `testdict1` with some subkeys implicitly,
* assign this dictionary to another one (`testdict2`),
* change a key value using `testdict1` and also `testdict2`

```
${params.global.testdict1.subKey1.subKey2} : 1,
"testdict2" : ${params.global.testdict1},
${params.global.testdict2.subKey1.subKey2} : 2,
${params.global.testdict1.subKey1.subKey2} : 3
```

Outcome is an error:

```
Reason: Could not set variable '${params.global.testdict2.subKey1.subKey2}' with value '2'! Reason
        str' object does not support item assignment
```

But why is it not possible to assign value **2**? Why is a string object involved here?

Because of the decision in
https://github.com/test-fullautomation/python-jsonpreprocessor/issues/214#issuecomment-1991447325

I would expect `subKey2` to have the integer value **3** (in both cases: `testdict1` and `testdict2`).

Another impact:

I translate the code to pure JsonPreprocessor:

```
${testdict1.subKey1.subKey2} : 1,
"testdict2" : ${testdict1},
${testdict2.subKey1.subKey2} : 2,
${testdict1.subKey1.subKey2} : 3
```

Result:

```
{'testdict1': {'subKey1': {'subKey2': 2}},
 'testdict2': {'subKey1': {'subKey2': 2}}}
```

No error in this case, but I would expect value **3** in both cases (instead of **2**).

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/214#issuecomment-1991995979

**Comment by HolQue** [comment]
Addendum:

The same with lists:

```
"testlist1" : [1,2],
"testlist2" : ${params.global.testlist1},
${params.global.testlist1}[0] : 3,
${params.global.testlist2}[1] : 4
```

Result:

```
Reason: Could not set variable '${params.global.testlist2}[1]' with value '4'! Reason
        str' object does not support item assignment
```

**Comment by HolQue** [comment]
The same in pure JsonPreprocessor:

```
"testlist1" : [1,2],
"testlist2" : ${testlist1},
${testlist1}[0] : 3,
${testlist2}[1] : 4
```

Here it works!

`{'testlist1': [3, 4], 'testlist2': [3, 4]}`

**Comment by namsonx** [comment]
Hello Holger,

This issue was fixed on stabi branch of JPP repository.
Could you please help me verify it?

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
