### ISSUE TITLE
Dictionary within a dictionary does not work

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#255]
Config:

```
"params" : {
            "global": {
                        "test" : {"001" : {"002" : "X"}}
                      }
           }
```

Result:

```
[ ERROR ] Could not convert: CConfig.ddictJson.001 = DotDict({'002': 'X'}) to dotdict.
Exception: invalid syntax (<string>, line 1)
```

Why is this not working? The same definition of "`test`" in JsonPreprocessor works fine.

**Comment by HolQue** [comment]
Addendum:

maybe caused by removed `globals()` within `CConfig` / `exec()`?

**Comment by namsonx** [comment]
Hello Hogler,

This is related to dotdict coverting in TestsuiteManagement, Python does not allow the  expression ```CConfig.ddictJson.001``` because identifiers (attribute names) cannot start with a digit.
In JP, it works becuase a dictionary object is not coverted to dotdict.
In the ticket https://github.com/test-fullautomation/python-jsonpreprocessor/issues/206, we're going to prevent user names a key started by digits.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

OK, when there is such a syntax restriction, we have to accept. But nevertheless, I do not understand this.

Instead of a dictionary within a dictionary, I can define a list inside a dictionary:

```
  "params" : {
              "global": {
                          // "test" : {"001" : {"002" : "X"}}
                          "test" : {"001" : ["002" , "X"]}
                        }
             }
```

Here we also have the number "001" as key name. And this works. What is the difference?

**Comment by test-fullautomation** [comment]
Hi Son,
as discussed, both is valid for creation of a dotdict.
If your dotdict fails, then it is a wrong implementation in the constructur.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I had updated the dotdict converter method as our discussion and created the pull-request for this update.

Thank you,
Son

**Comment by test-fullautomation** [comment]
very good!

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
