### ISSUE TITLE
Differences between TestsuitesManagement and JsonPreprocessor results

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#261]
Please refer to https://github.com/test-fullautomation/python-jsonpreprocessor/issues/262

In four cases the result of TestsuitesManagement deviates from JsonPreprocessor result.

**(5)**

`"A\"B" : "value"`

JsonPreprocessor: {'A"B': 'value'}
Python load(): {'A"B': 'value'}
TestsuitesManagement: UNKNOWN - Exception occurred.

**(6)**

`"para\u0020m" : "value"`

JsonPreprocessor: {'para m': 'value'}
Python load(): {'para m': 'value'}
TestsuitesManagement: UNKNOWN - Exception occurred.

**(11)**

`"param\uD800" : "value"`

JsonPreprocessor: UnicodeEncodeError: 'utf-8' codec can't encode character '\ud800' in position 30: surrogates not allowed
Python load(): UnicodeEncodeError: 'utf-8' codec can't encode character '\ud800' in position 34: surrogates not allowed
TestsuitesManagement: UNKNOWN - Exception occurred.

**(12)**

`"1*~@#$%^&*(')_+=><?/\"ÄÖÜ.ß.€.考.𠼭.𠼭": "value"`

JsonPreprocessor: {'1*~@#$%^&*(\')_+=><?/"ÄÖÜ.ß.€.考.𠼭.𠼭': 'value'}
Python load(): {'1*~@#$%^&*(\')_+=><?/"ÄÖÜ.ß.€.考.𠼭.𠼭': 'value'}
TestsuitesManagement: UNKNOWN - Exception occurred.

**Comment by namsonx** [comment]
Hello Holger,

As we already discussed, JPP and TSM are 2 separated packages.

In ticket [#JPP_206](https://github.com/test-fullautomation/python-jsonpreprocessor/issues/206), we agreed that the naming convention of JPP is followed by the naming convention of JSON format. 

Regarding this ticket, I will implement a feature to check variables' name format when loading .jsonp configuration files based on the naming convention of RobotFW.

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
