### ISSUE TITLE
Changed behavior of TestsuitesManagement (exception)

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#262]
With latest changes in stabi branch, the behavior of the TestsuitesManagement changed in some cases.

Previously this has been accepted:

`"param+1" : "value"`

or

`"param-1" : "value"`

Now this causes:

`UNKNOWN - Exception occurred.`

But if this is not a violation of Robot Framework naming conventions, it should still be allowed. Or I expect a naming convention error message.

**Comment by HolQue** [comment]
At least I can do this:

```
Set Test Variable    ${param-2}    param-2 value
log    value of param-2 is: ${param-2}
```

This is accepted.

**Comment by namsonx** [comment]
Hello Holger,

I updated the behavior of TSM.

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
