### ISSUE TITLE
Access to class variables in CConfig()

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#263]
The class `CConfig()` defines variables as class variables (not instance variables).

Some of them are accessed with `self` instead of the class name, e.g.: `self.bConfigLoaded, self.sConfigName, self.sProjectName` ...

Is there a certain reason to do it in this way? Usually recommend is to use the class name for class variables: `CConfig.bConfigLoaded`.

**Comment by namsonx** [comment]
Hello Holger,

I move the class variables into the constructor method ```__init__()``` of  ```CConfig()``` class via [commit e1e0c206e8ca](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/commit/e1e0c206e8ca699dde58cfdeda22be1ef1eb6c22).

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
