### ISSUE TITLE
Synchronization of error messages between JsonPreprocessor and TestsuitesManagement

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#264]
Simply an idea:

The JsonPreprocessor detects an error (`<error>`), this error has an impact (`<impact>`). The JsonPreprocessor generates an error message in this way: `error_message = "<error>\n<impact>"`.

I would say, in standalone usage the line breaks in error message do not hurt. But in context of TestsuitesManagement the error messages are logged in a way that every line starts with a timestamp. Here manual line breaks should be avoided.

Therefore TestsuitesManagement should do a `split()` of line breaks in all error messages provided by JsonPreprocessor.

The logic behind this is: The first element in the list of split results in every case is the error - and has to be logged as `ERROR`. All following elements in the list are additional informations (like impacts) - and have to be logged as `INFO` or immediately as `UNKNOWN` (this depends on the use case).

How to realize this in TestsuitesManagement I have described in
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/258

Please refer also to

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/259#issuecomment-2039198861

**Comment by test-fullautomation** [comment]
Hi Holger,
is for me a good proposal.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger,

The solution of this ticket was implemented in commit [b3a65f87c05ec](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/commit/b3a65f87c05ec50794ca4d04a322ebba73b09e6c).
Could you please help me check?

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
