### ISSUE TITLE
Missing suite metadata

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#283]
In case of the configuration level is 2, the log file contains a bunch of lines defining the meta data:

```
INFO - Set suite metadata 'project' to value ...
...
INFO - Set suite metadata 'version_test' to value ...
```

In case of the configuration level is 1, these lines are missing.

Why?

I would expect that all values are set (if available) - independent from the configuration level.

**Comment by namsonx** [comment]
Hello Holger,

I implemented the change for this ticket and pushed to stabi branch.

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.1 [06.09.24](jsonpreprocessor / tsm)**

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
