### ISSUE TITLE
Robot Framework does not react on any log level provided in command line

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#309]
Hi Son,

very good. Especially I like the idea to keep the detailed `jsonschema.exceptions.ValidationError` information at DEBUG level. This is really helpful. I made some tries with log level USER and DEBUG in extended version. It works. With log level INFO the details are not logged any more.

Then I switched to the original version. Now I am confused. Because I see the same `jsonschema.exceptions.ValidationError` also in case I run the test with log level INFO. I took a look at my listings in this issue. Already there all traceback output is marked as DEBUG. I completely overlooked this. _Why is a DEBUG message printed in log level USER?_ I tried some other log levels in command line. There are no differences in the log output. The Robot Framework does completely not react on any log level provided in command line. Except I use an invalid log level. This causes an error. I have no idea what is going one here. 

OK, two things:

1. My guess is that these effects have something to do with the different Robot Framework versions behind the original and the extended version. @namsonx : Would be great if you can spend some time to try to reproduce my log level findings w.r.t the original version.
2. In my opinion the issue is solved in the Testsuites Management. Therefore the issue can be closed.

Further measures w.r.t. the different versions of the Robot Framework core should be handled in other issues (if required).

_Originally posted by @HolQue in https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/302#issuecomment-2491237503_

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
can you please check this?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello @HolQue , hello @test-fullautomation 

The log level in RobotFW just affects the ```<log>.html``` when executing robot test.

When executing robot test, if you enable option ```-b <debug_log_file>.log``` then ```DEBUG``` log always presents in ```<debug_log_file>.log``` file event you set ```--loglevel INFO``` or ```--loglevel NONE```.

In the ```<log>.html``` file:
   - ```DEBUG``` message will be printed when you set ```--loglevel``` as ```TRACE``` or ```DEBUG```
   - In case you set ```--loglevel``` as ```INFO```, ```WARN```, ```ERROR```, or ```NONE```,  ```DEBUG``` message will not be printed.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

what you explain is completely in opposite to what I observed up to now. My understanding is that also the debug log file
follows the rules of log levels. The debug log file does not contain DEBUG messages only because the file is supposed to be a "debug log". What is logged depends on the log level defined in command line.

I repeated my tests with the latest installers: RobotFramework_AIO_setup_0.13.1.15_original.exe and RobotFramework_AIO_setup_0.13.1.15_extended.exe.

**Summary:**

The behavior of the extended installation is like expected (DEBUG messages printed only in case of this trace level is requested in command line). The behavior of the original installation deviates from the extended installation and is not like expected
(DEBUG messages printed also in case of trace level USER is requested in command line).

This behavior of the original installation is new to me. Why do the two versions behave so differently?

**What is the difference between the original version and the extended version? The Robot Framework itself!**

**Seems that in the new version of the Robot Framework used in the original version, the debug log file behavior changed.**

**Not nice: This completely destroys our log level USER concept!**

Below my test results in detail.

* Installation: RobotFramework_AIO_setup_0.13.1.15_original.exe (original / BIOS)

GOODCASE: simple log message in robot file

robot file

Log    ======= DEBUG message    DEBUG

Execution with

--loglevel=INFO

Result: DEBUG message logged in debug log file

DEBUG - ======= DEBUG message

Execution with

--loglevel=DEBUG

Result: DEBUG message logged in debug log file

DEBUG - ======= DEBUG message

* Installation: RobotFramework_AIO_setup_0.13.1.15_original.exe (original / BIOS)

BADCASE: version control error in JSON file

Execution with

--loglevel=INFO

Result in debug log file (extract)

ERROR - Wrong use of max/min version control in configuration.
FAIL - Version control error!!!
DEBUG - Traceback (most recent call last):

Execution with

--loglevel=DEBUG

Result in debug log file (extract)

ERROR - Wrong use of max/min version control in configuration.
FAIL - Version control error!!!
DEBUG - Traceback (most recent call last):

* Installation: RobotFramework_AIO_setup_0.13.1.15_extended.exe (extended / BIOS)

GOODCASE: simple log message in robot file

robot file

Log    ======= DEBUG message    DEBUG

Execution with

--loglevel=INFO

Result: no DEBUG message in debug log file

Execution with

--loglevel=DEBUG

Result: DEBUG message logged in debug log file

DEBUG - ======= DEBUG message

* Installation: RobotFramework_AIO_setup_0.13.1.15_extended.exe (extended / BIOS)

BADCASE: version control error in JSON file

Execution with

--loglevel=INFO

Result in debug log file (extract)

ERROR - Wrong use of max/min version control in configuration.
UNKNOWN - Version control error!!!

But no: DEBUG - Traceback (most recent call last): !!!

Execution with

--loglevel=DEBUG

Result in debug log file (extract)

ERROR - Wrong use of max/min version control in configuration.
UNKNOWN - Version control error!!!
DEBUG - Traceback (most recent call last):

**Comment by HolQue** [comment]
Most probably there is nothing more we can do here. Therefore the issue can be closed.

Further investigations should be part of other issues (if required).

**Comment by HolQue** [comment]
Addendum: This issue is completely caused by my misunderstandings! I am the one who implemented the reduction of the log files content and the log level USER. From this moment on this behavior becames a 'standard' for me. And I was not aware any more, that this is only a standard in our extended version, but not in the original version. It took some time for me to get this understanding back in my mind ;-)

This issue is invalid!

**Comment by test-fullautomation** [comment]
no problem...
