### ISSUE TITLE
Term "ROBFW"

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#33]
The term "ROBFW" is used several times in the README. Is this a usual term? Or better use the full version "RobotFramework AIO"?

**Comment by test-fullautomation** [comment]
Hi Holger,
thank you for the finding.
Correct is "RobotFramework AIO" except of we write explicitely about the Robot Framework Core, then it would be "Robot Framework".
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
@Son: Please look into this.

**Comment by test-fullautomation** [comment]
Hi Son,
by when can I get an update from you?
Thank you,
Thomas

**Comment by namsonx** [comment]
> Hi Son, by when can I get an update from you? Thank you, Thomas

Hello Thomas,

I already updated this together with the[ pull-request](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/36) of improvement documentation.
I'm sorry because I forgot update the status here.

Thank you,
Son
