### ISSUE TITLE
code blocks

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#34]
The text in README would be easier to read when separate code blocks are used instead of inline code - at least when this causes line breaks within the code. Abbreviations like "Ex:" should be avoided.
See code.pdf
[code.pdf](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/files/9681930/code.pdf)

**Comment by test-fullautomation** [comment]
Hi Son,
please look into this.
Thank you,
Thomas

**Comment by test-fullautomation** [comment]
Hi Son,
by when can I get an update from you?
Thank you,
Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I already resolved this ticket in the [pull-request](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/36), this pull-request was merged.
Sorry for this confusion.

Thank you,
Son
