### ISSUE TITLE
link outdated

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#35]
The link to the PDF is outdated and invalid. As long as this PDF is still under construction, the link in the README should be removed.
[outdated.pdf](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/files/9682091/outdated.pdf)

**Comment by test-fullautomation** [comment]
Hi Son,
please look into this.
Thank you,
 Thomas
