### ISSUE TITLE
invalid code blocks

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#38]
README.rst

The markdown directive “code-block” belongs to Sphinx. Because we do not use Sphinx any more this directive is invalid for us. The rst equivalent name of this directive is
                        .. code::
Please do not use “code-block” any more.

**Comment by test-fullautomation** [comment]
Hi Son,
by when can I get an update from you?
Thank you,
Thomas

**Comment by namsonx** [comment]
Hello Thomas,

This issue is solved in the pull-request #45 

Thank you,
Son
