### ISSUE TITLE
code block "robot" not known in VSCode rst extension

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#39]
The README.rst of the testsuites management contains the following code:
.. code-block:: robot

Pandoc has luckily no problems with the name "robot" of the code directive. Also GitHub has no problems. The README files are rendered properly.

But the corresponding extensions of VSCode have problems with the name robot. They do not know the name "robot".
As long as they do not know this name we should use for Robot Framework code listings the common version of this code directive (without the name of the language):
                        .. code::

**Comment by test-fullautomation** [comment]
Hi Son,
by when can I get an update from you?
Thank you,
Thomas

**Comment by namsonx** [comment]
Hello Thomas,

This issue is solved in the pull-request #45 

Thank you,
Son
