### ISSUE TITLE
Thoughts about three dot syntax

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#46]
Thinking about: There is a relative relationship between the Suite Setup and the variants file:

`Suite Setup    testsuites.testsuite_setup    ./config/variants_config.json`

Within variants_config.json there is a relative - and also dynamic (three dots) - relationship between the test suite and the folder in which the parameter configuration files can be found:

`"path": ".../config/"`

Why is it implemented in this way? I see two disadvantages:

1. It is really long winded to explain the users that this path ".../config/" is not relative to the file variants_config.json
who contains this path, but relative to the position of the test suite who imports this file variants_config.json.

2. In case of the test suite is moved in the file system (level up or level down), either the file variants_config.json also has to be moved or the path to this file

`Suite Setup    testsuites.testsuite_setup    ./config/variants_config.json`

inside the test suite needs to be adapted. The outcome is: Adaptions are necessary.

Why not other way round?

We introduce a fix relative relationship between the variants file and the path to the folders containing the parameter configuration files:

`"path": "./config/"`

And we make the path to the variant file inside the test suite dynamic relative:

`Suite Setup    testsuites.testsuite_setup    .../config/variants_config.json`

The advantages are:

1. Every path is relative to the file containing the path - this is much easier to understand
2. In case of the test suite is moved in the file system (level up or level down), no further adaptions are necessary

Possible?

**Comment by test-fullautomation** [comment]
Hi Holger,
after discussion I understood the proposal.
I will create a requirement from this issue.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
related to #166

**Comment by HolQue** [comment]
So much cool:

It works:

`Suite Setup    testsuites.testsuite_setup    .../config/variants_config.json`

Great!!!!!

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by HolQue** [comment]
Tiny hint only:

The interface description of `class CConfig():` needs to be adapted:

w.r.t.:  `"path": ".../config/"`

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
