### ISSUE TITLE
Config files in suite setup

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#47]
We have two different types of JSON configuration files: the variants configuration file and the common parameter files.

The first one is an input parameter of the suite setup. The second one is a command line parameter.

How about this option?

_Passing a certain parameter file to the suite setup (instead of the variants configuration)._

This option is interesting for all who do not want to overload the command line and also do not need any variants handling.

I gave it a try. But the outcome is an error:

[ ERROR ] Testsuite management is in configuration level2.
[ ERROR ] The file './config/exercise-02_config_variant1.json' has no default config or wrong testsuite config format for level 2
[ ERROR ] Testsuite will run with default config file:

Is this a bug or is this option simply not implemented?

When it is possible to put a parameter file directly in the command line, why not also directly to the suite setup?

**Comment by test-fullautomation** [comment]
Hi Holger,
after discussion I close the ticket because if somebody would use this feature he/she would potentially create a testsuite which may need later larger rework when he/she want to introduce variant handling.
Thank you,
 Thomas
