### ISSUE TITLE
Command line does not overwrite json configuration

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-testsuitesmanagement#49]
The Robot Framework allows to define variables in command line (by '--variablefile' and '–variable'). The documentation tells that the command line has higher priority than variables with same name defined in tests.

In opposite to that it is not possible to use the command line to overwrite variables that are already defined within a json configuration file of the TestsuitesManagement.

TestsuitesManagement must only overwrite variables if not already defined by command line '--variablefile' or '–variable'.

**Comment by test-fullautomation** [comment]
Hi Son,

a variable/parameter created by --variablefile or variable must have highest priority. It must overwrite variables created/configured by Testsuitesmanagement, directly or by means of local config. Command line overwrites all.

Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I will update the behavior of loading configuration feature.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Thomas and Holger,

The fix for this issue #51 already merged, could you please check and close this issue.

Thank you,
Son

**Comment by test-fullautomation** [comment]
already merged.
