### ISSUE TITLE
Block multiple imports of json configuration

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-testsuitesmanagement#5]
Hi Son,

I set the status back to "in work".

As per our discussion today. If the __init__.robot file loads a configuration, then the testuites (robot files) must startup with a clean environment. Only robotframework builtins are allowed till a level2,3 or 4 configuration is loaded.

Goal is to have zero implicitely done interference between robot files. When we want or need this later we will find an explicite way by means of syntax elements / keywords / ... to do this.

If a testsuite (robot file) loads multiple files, then the test run must abort with an error message due to multiple loaded config files.

Thank you,

 Thomas

**Comment by test-fullautomation** [comment]
Hi Son,

O.K. according to the current limitations which robot framework core give us:

Let us go for the moment with level 2 variable updates if a .robot file contains a level 2 definition.
But: Each .robot file can only have one level 2 definition. 
        If there are other level 2 definitions within one .robot file, then this would be an error -> abort of test execution.

Please update your UML diagram accordingly.

Once the robot framework core supports better ways we will adapt testsuites-management accordingly.

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Son,
where do I find the UML diagram with the nice overview.
Should be part of the documentation.
Thank you,
 Thomas

**Comment by namsonx** [comment]
> Hi Son, where do I find the UML diagram with the nice overview. Should be part of the documentation. Thank you, Thomas

Hello Thomas,

    Sure, I will upload UML diagram to testsuites-management repository.

Thank you,
Son

**Comment by test-fullautomation** [comment]
This issue is solved.
