### ISSUE TITLE
configuration files need to support utf-8 characters

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-testsuitesmanagement#50]
> Is it a requirement for configuration files to support Unicode characters?
> 
> I gave it a try:
> 
> ${params}['global']['teststring_bench'] : "I am the bench1 SälfTest.ß.€.考.𠼭.𠼭 configuration of exercise 06"
> 
> But the special characters in the middle of the string are not displayed correctly in log file and also not in console:
> 
> teststring_bench : I am the bench1 SÃ¤lfTest.ÃŸ.â‚¬.è€ƒ.ð ¼­.ð ¼­ configuration of exercise 06

Hello Holger,

Unfortunately, it does not support Unicode characters yet, you can create a ticket for me to implement it in python-jsonpreprocessor package.

_Originally posted by @namsonx in https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/45#issuecomment-1340898098_

**Comment by test-fullautomation** [comment]
Hi both,
I assume you mean UTF-8 characters.
Yes, we need to support UTF-8 files and accordingly proper UTF-8 data processing.
I assume UTF-8 input by JSON must become unicode on python/robot dictionary level, so you must decode accordingly.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Son,
what is the status here?
This is an important issue.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas and Holger,

I created [new pull-request](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/43) to fix this issue on python-jsonpreprocessor repository.

Thank you,
Son

**Comment by HolQue** [comment]
Greetings from "SälfTest.ß.€.考.𠼭.𠼭"

Works well in jobs/1681416

**Comment by test-fullautomation** [comment]
solved with already merged #43
