### ISSUE TITLE
Contradictory variants setting in command line

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#52]
There are two ways available to define a variant in command line of Robot Framework. What will happen, when someone
mix up these ways (accidently)?

The following makes no sense and is also contradictory - but possible:

`--variable variant:"variant1" --variable config_file:"./config/exercise-06_config_variant2.json"`

The result is: level 1, variant 2

It is clear to me that internally there must be an order to compute command line variables. And it seems that "config_file" is computed before "variant". But even so, it makes no sense to define both.

Therefore the test suites management should make a deeper check of what is given in command line. 

And if both variables are given, the "variant" and the "config_file" (independent from content), then
the test suites management should throw an error. Because in this case the intention of the user is not clear.

**Comment by test-fullautomation** [comment]
> And if both variables are given, the "variant" and the "config_file" (independent from content), then
> the test suites management should throw an error. Because in this case the intention of the user is not clear.

Hi Son,
please implement accordingly.
If somebody hands over a by command line a config file, then "variant" makes no sense. The user want to use this config file, whatever the content is.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

Please find my pull-request #59 for this enhancement.

Thank you,
Son

**Comment by HolQue** [comment]
I installed namsonx/improvement/issue52/contradictory_variants

But I still do not get an error message in case of an contradictory variants setting.

**Comment by HolQue** [comment]
Feature works properly in namson/features/testing_branch
