### ISSUE TITLE
Command line computation order unclear

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#53]
A common rule is: Command line has higher priority than other settings.

But we already have several possibilities to select parameter values in command line only.

Combinations are thinkable in which the same parameters are involved - but with different values:

For example:

(1)
`--variable myparam:"myvalue" --variable config_file:"./myparamsconfig.json"`

(2)
`--variable myparam:"myvalue" --variable config_file:"./myparamsconfig.json" --variable local_config:"./mylocalconfigparams.json"`

(3)
`--variable myparam:"myvalue" --variable variant:"myparamsvariant" --variable local_config:"./mylocalconfigparams.json"`

(4)
`--variable myparam:"myvalue" --variable local_config:"./mylocalconfigparams.json"`

What is the order of computation in these cases? Who will finally define the value of "myparam"?

**Comment by test-fullautomation** [comment]
Hi Holger,

puh 🥇 

I have concerns that we can in this case determine which value will be finally loaded.
It depends how Robot Framework Core processes the command line arguments. The last processed one will be the winner.

I think in this case it is on the user to use the interface in a meaningful way.

Thank you,
 Thomas

**Comment by HolQue** [comment]
Oh what a pity. But I still have doubts. Do we really have no chance for better clarification? We cannot leave our customers alone with this situation.

At least I would expect that we have the variables "config_file", "local_config" and "variant" under our own control because these variables are introduced by the RobotFramework_TestsuitesManagement. Therefore we can check the content and we can define an order.

Maybe only in case of this mechanism is used to define any other variable (like --variable myparam:"myvalue") it is out of control for us - in case of it is not possible for the RobotFramework_TestsuitesManagement to get access to a list of all runtime parameters of the Robot Framework.

But even in this case it's quite easy to handle this - because we can reduce all measures to a simple rule, communicated to the users. The rule is:

In case you use "config_file", "local_config" or "variant" in command line, you must not also use the --variable mechanism to define a value for any of the configuration parameter (because this will lead into an undefined state)!

Something like that.

Possible?

**Comment by test-fullautomation** [comment]
Hi Holger,

Hm...
What could be a priority list is (highest priority first):
1. local config
2. config_file

I'm not sure about variant. variant can only work if config_file has a variant configuration.
So this should be handled anyhow by testsuites management error checks?

Thank you,
 Thomas

**Comment by HolQue** [comment]
Modified by Thomas after discussion:

highest prioriy first:
1. --variable
2. local config
3. config_file or variant

**Comment by HolQue** [comment]
Feature clear to me now.
