### ISSUE TITLE
Minimum_version as well as Maximum_version must be optional

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-testsuitesmanagement#54]
another important change required for 0.6.0 version.
Minimum_version as well as Maximum_version must be optional.

All must be possible.
- [ ] Minimum and Maximum version defined.
- [ ] Only Minimum version defined.
- [ ] Only Maximum version defined.
- [ ] Default: no Minimum, no Maximum version defined.

**Comment by namsonx** [comment]
Hello Thomas,

This enhancement is implemented in pull-request #60 

Thank you,
Son

**Comment by test-fullautomation** [comment]
merged already with #63
