### ISSUE TITLE
Missing "re" module in LibListener

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#55]
Compared to the previous version of the LibListener in the current version the line

import re

is removed, but "re" is still used.

=> [ ERROR ] Calling method '_start_suite' of listener 'LibListener' failed: NameError: name 're' is not defined

**Comment by namsonx** [comment]
Hello Holger,

Sorry for my mistake! **import re** was added in pull-request #45  
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/blob/namson/task/localconfig_support_required/RobotFramework_Testsuites/Utils/LibListener.py

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
I assume this is fixed with #63?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hi Thomas,

Yes, I already merged it to HolQue/task/documentation_updates_and_fixes branch.

Thank you,
Son

**Comment by test-fullautomation** [comment]
merged with #63
