### ISSUE TITLE
Final maintenance of readme and documentation

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-testsuitesmanagement#57]
Hi Son,

I handover the final maintenance of readme and documentation to Holger. This is to avoid long lists of findings.
@namsonx : Please provide as soon as possible #44 as this has effects on the whole documentation, too.
                    Please concentrate on the features and fixes.

@HolQue : documentation is on you now.

Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

Well noted!

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Holger,
I assume this can be closed as it was part of #63.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

not yet!

The README is done; the complete rework of RobotFramework_TestsuitesManagement.pdf is ongoing and finished most probably tomorrow.

Also the handling of new introduced variable ROBOT_LOCAL_CONFIG has to be explained in tutorial in more detail.

**Comment by HolQue** [comment]
Ready for 0.6.0 with https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/75

All further possible enhancements in version > 0.6.0.

**Comment by test-fullautomation** [comment]
O.K. then I let this taks open.

**Comment by HolQue** [comment]
Status:
* Common part of RobotFramework_TestsuitesManagement.pdf finished
* New local config feature explained in PDF and in 900_building_testsuites tutorial
* 900_building_testsuites tutorial extended by final example (with this the tutorial task is finished)

Open:
* Rework of interface descriptions of RobotFramework_TestsuitesManagement
