### ISSUE TITLE
History incomplete

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#64]
A lot of new features have been developed, but the RobotFramework_TestsuitesManagement.pdf history is still on "Initial version" - and therefore should be updated.

Reference:
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/tree/HolQue/task/documentation_updates_and_fixes

**Comment by test-fullautomation** [comment]
Hi Son,
what is the status here?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I will update version history for robotframework-testsuitesmanagement repository.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Thomas and Holger,

I have just created pull-request #74 to update version and history.
I just increased new version of testsuitesmanagement package from 0.2.2 to 0.3.0 with new feature local configuration. 
Please give me your comment regarding to this new version number?

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
we are even incompatible with the improved null/None handling.
So 0.3.0 is sure meaningful.,
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
merged already #74
