### ISSUE TITLE
Code efficiency

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#65]
LibListener.py

In lines after:
`elif 'ROBOT_LOCAL_CONFIG' in os.environ:`
several times
`os.environ['ROBOT_LOCAL_CONFIG']`
is accessed.

But it would be more efficient to use os.environ['ROBOT_LOCAL_CONFIG'] only once. A separate variable should be used for the path.
And the path should be normalized.

Reference:
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/tree/HolQue/task/documentation_updates_and_fixes

**Comment by namsonx** [comment]
Hello Holger,

I cherry-picked the [commit](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/63/commits/f952aedcc80ab69ed1a6679f892d3e0716ba400e) to branch [HolQue/task/documentation_updates_and_fixes](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/tree/HolQue/task/documentation_updates_and_fixes)

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
what is the status here?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
this is part of #63
