### ISSUE TITLE
Inconsistent log output

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#66]
The log output contains a strange mixture of relative and absolute paths and also of slashes and backslashes:

INFO - Parameters loaded from './config/exercise-07_config_variant1.json'
INFO - Suite Path: C:\RobotTest\projects\ROBFW_AIO\robotframework-tutorial\900_building_testsuites\exercise-07\
INFO - CfgFile Path: ./config/exercise-07_config_variant1.json
INFO - Local config file: C:\RobotTest\localconfig\localconfig_defaultbench.json

To ease the debugging:

* All relative paths should be converted to absolute paths
* All paths should be normalized (finally containing slashes only)

Example:
Also with not really well prepared paths like this:
`set ROBOT_LOCAL_CONFIG=C:/RobotTest\localconfig/../localconfig\localconfig_defaultbench.json`
the log output is:
`INFO - Local config file: C:/RobotTest\localconfig/../localconfig\localconfig_defaultbench.json`
But such kind of content should be avoided in log files. Therefore a normalization of all input paths is required.

Reference:
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/tree/HolQue/task/documentation_updates_and_fixes

**Comment by namsonx** [comment]
Hello Holger,

I created the [new commit](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/63/commits/6876766ba451cad74dc76c6f7ed3899f484e0c65) to resolve this issue.

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved with #63.
