### ISSUE TITLE
Configuration level warning

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#68]
Still configuration level 1 causes a warning, but level 4 not.

It should be other way round.

Reference:
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/tree/HolQue/task/documentation_updates_and_fixes

**Comment by namsonx** [comment]
Hello Holger,

I created [new commit](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/63/commits/16c9cc16236bb6f4219fcf5b87a3395729e63056) for this issue.

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved with #63
