### ISSUE TITLE
Local configuration issue with single quotes

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#69]
In opposite to the already fixed standard configuration files it is not possible to use single quotes inside a local configuration file.

Example:
`${params}['global']['teststring'] : "I am the 'local' configuration"`

Causes:
```
ERROR - Loading local config failed! Reason: Could not set variable 'params['global']['teststring']' with value 'I am the 'local' configuration'!
UNKNOWN - Unknown exception occurs. Details: Could not set variable 'params['global']['teststring']' with value 'I am the 'local' configuration'!
```

* Single quotes should be possible also in local configuration
* The log file contains two error messages with mostly the same content. This redundancy should be avoided
* The variable name is incomplete (${} is missing): 'params['global']['teststring']' instead of '${params}['global']['teststring']'

Reference:
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/tree/HolQue/task/documentation_updates_and_fixes

**Comment by namsonx** [comment]
Hello Holger,

This requirement should belong to [python-jsonpreprocessor](https://github.com/test-fullautomation/python-jsonpreprocessor) package.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Tracket with
https://github.com/test-fullautomation/python-jsonpreprocessor/issues/40
