### ISSUE TITLE
test functionality after sphinx adaptations.

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-testsuitesmanagement#7]
Hi Son,
I merged https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/6
from Holger. This was required that sphinx build works properly.
Please test all your functionality. Please also take from now care that html and pdf generation works after changes.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hi Thomas,

      I do the functionality test with this pull-request and unfortunately all Testsuites-Management are not work. 
      I saw Holger comment out "import RobotFramework_Testsuites" in many python modules, I observed Holger did adding again this import in merged #9 but it's still missing somewhere.
      Currently I still observe issue "NameError: name 'RobotFramework_Testsuites' is not defined"

Thank you,
Son

**Comment by test-fullautomation** [comment]
Closed, this is redundant with #8
