### ISSUE TITLE
Version control not executed

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#71]
What happened with the version control mechanism?

The following invalid combinations are accepted and the executed tests are passed:

INFO - Set suite metadata 'version' to value '0.5.2'.
INFO - Maximum_version : 0.2.0
INFO - Minimum_version : 0.2.0

INFO - Set suite metadata 'version' to value '0.5.2'.
INFO - Maximum_version : 0.1.0
INFO - Minimum_version : 0.9.0

I added a breakpoint, but verifyRbfwVersion in CConfig is not executed.

Reference:
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/tree/HolQue/task/documentation_updates_and_fixes

**Comment by namsonx** [comment]
Hello Holger,

Version check now is optional according to new requirement from Thomas #54 
From ROBFW-AIO version 0.6.0, version control mechanism is just activated in case user execute robot run with --variable version_check:${True}

By default, version check is deactivated.

Thank you,
Son

**Comment by HolQue** [comment]
Completely strange!

The requirement tells: "Minimum_version as well as Maximum_version must be optional."

In my opinion this means:
* version(s) defined => version control active
* both versions not defined => version control not active

Why do we need an additional variable? It's redundant only.

What has to happen in case of a user wants to have the version control activated per default? Does this user really has to set this version_check variable in every command line for every test execution? This would be so much long winded. Or is there the possibility to add this parameter in any configuration file permanently? However: long winded and not necessary.

And why this: ${True}? Why do we need the dollar syntax within a command line at operating system level? Simply True should be enough.

**Comment by namsonx** [comment]
Hello Holger,

For the requirement "Minimum_version as well as Maximum_version must be optional.", it's better in case you discuss directly with Thomas when he backs.
And why this : ${True}? This issue because I defined the version_check with boolean datatype, so the syntax of Robot requires ${} otherwise it will consider the value is string.
Yes, we can simply use True instead of ${True}, and I just need 15 minutes to create new commit for this change :)

Thank you,
Son

**Comment by HolQue** [comment]
I gave it a try: Also without dollar syntax it works:
```
--variable version_check:True
--variable version_check:true
```

With this outcome:

```
The configured minimum Robotframework AIO version                 '5.0.0'
is younger than the configured maximum Robotframework AIO version '0.0.0'
Please correct the values of 'Maximum_version', 'Minimum_version' in config file

Please install the required RobotFramework AIO version.
You can find an installer here: \\bosch.com\dfsrb\DfsDE\DIV\CM\DI\Projects\Common\RobotFramework\Releases
```

But what happened? It is detected that the version numbers do not fit together and therefore are invalid. Therefore a hint is given that the values have to be corrected. That is OK. But out of this we cannot conclude that the RobotFramework AIO needs to be reinstalled! At first we need valid version numbers, than we can use them for a version control. And only in case of this fails we need to give the installation hint. Otherwise not!

=> In case of invalid version numbers the second part of the error message containing the installation hint, should be removed.

And typing mistake in error message: Robotframework AIO

**Comment by HolQue** [comment]
Some further tries:

Activates the version check properly:
--variable version_check:${True}
--variable version_check:${true}
--variable version_check:True
--variable version_check:true

Deactivates the version check properly:
--variable version_check:${False}
--variable version_check:${false}

Version check not deactivated (= it's active):
--variable version_check:False
--variable version_check:false

Even invalid values without dollar operator activate the version check:
--variable version_check:anything

Invalid values with dollar operator do not activate the version check:
--variable version_check:${anything}

This activates the version check:
--variable version_check:${}

Something went wrong completely with the internal value handling.

Internally the variable version_check needs to be checked explicitely against [None, True, true, False, false].

With None is the internal default value in case of version_check is not set anywhere.

No other value must be accepted! Any other value has to cause an error message and has to quite the test execution with result UNKNOWN.

But like I already mentioned: I do no see any reason for 'version_check'.

**Comment by HolQue** [comment]
Because now the version check can be switched on and off I would like to have this mentioned in the log file.

Like:

* "Running without version check"
* "Version check passed"
* In case of version check failed => already implemented error message

**Comment by HolQue** [comment]
Tiny hint only:

Instead of

`The configuration requires maximum Robotframework AIO version '0.2.0'`

maybe it is better to focus on test execution with:

`The test execution requires maximum RobotFramework AIO version '0.2.0'`

Because that's it! That there is a configuration behind the execution is not really relevant here. It is not the configuration itself, that requires.

**Comment by HolQue** [comment]
`Maximum_version` and `Minimum_version` are optional now in parameter configuration file.

But when I activate the version check in command line with
`--variable version_check:${True}`
and the parameter configuration file does not contain `Maximum_version` and `Minimum_version`, then this is ignored completely: No version check, no error message.

But this use case should cause an error message - together with test result UNKNOWN.

**Comment by HolQue** [comment]
This is the outcome of making parameters optional together with incomplete value checks:

```
  "Maximum_typing_mistake" : "0.2.0",
  // "Minimum_version" : "0.9.0",
```

Outcome: No version check, no error message. Not OK.

Consequence: It is not sufficient to check if all required parameters are defined. It has also be checked if the user defines any other parameter, that is not supported. This would detect e.g. typing mistakes like `Maximum_typing_mistake`.

Such a check should be possible because luckily all user defined parameters are inside the separate key params:global. Therefore only the top level keys within parameter configuration files need to be checked for invalid key names.

**Comment by HolQue** [comment]
How about this: We make the versions mandatory again but consider to set the values to `None` or `null`:

```
"Maximum_version" : None,
"Minimum_version" : None,
```

The advantage would be: Both parameters are present (and therefore visible), (and also must be present) within the parameter configuration file in every case. Such code would be much easier to capture and to understand.

And what the user decides what he does not want ho have, he sets to `None `or `null`. And the reaction of the code can be taken out of the code immediately (in opposite to when additional runtime elements like
`--variable version_check:${True}`
are involved.

**Comment by HolQue** [comment]
I gave it a try with:

```
  "Maximum_version" : null,
  "Minimum_version" : null,
```

Outcome:

`[ ERROR ] Parameter 'Maximum_version' in JSON configuration file is not allowed due to: None is not of type 'string'`

(same with value `None`)

This error message is strange. Why shall the parameter itself not be allowed because of a wrong data type?
The parameter is allowed. And `null` is a valid data type in JSON. And the error message should reflect the root cause of the problem properly: Because of the parameter is initialized with value `null`, the error message should not tell about an invalid `None`.

I know that internally all `null` are converted to `None`, but the checks should be applied to the original values before the conversion.

**Comment by HolQue** [comment]
`"Maximum_version" : "0..",`
causes
`[ ERROR ] Parameter 'Maximum_version' in JSON configuration file is not allowed due to: '0..' does not match '^\\d+\\.\\d+\\.\\d+$'`

OK, now I understand: This "is not allowed" is only a wording issue.

Please fix this error message. Something like "invalid value" instead of "parameter ... is not allowed"

**Comment by ngoan1608** [comment]
> I gave it a try: Also without dollar syntax it works:
> 
> ```
> --variable version_check:True
> --variable version_check:true
> ```
> 
> With this outcome:
> 
> ```
> The configured minimum Robotframework AIO version                 '5.0.0'
> is younger than the configured maximum Robotframework AIO version '0.0.0'
> Please correct the values of 'Maximum_version', 'Minimum_version' in config file
> 
> Please install the required RobotFramework AIO version.
> You can find an installer here: \\bosch.com\dfsrb\DfsDE\DIV\CM\DI\Projects\Common\RobotFramework\Releases
> ```
> 
> But what happened? It is detected that the version numbers do not fit together and therefore are invalid. Therefore a hint is given that the values have to be corrected. That is OK. But out of this we cannot conclude that the RobotFramework AIO needs to be reinstalled! At first we need valid version numbers, than we can use them for a version control. And only in case of this fails we need to give the installation hint. Otherwise not!
> 
> => In case of invalid version numbers the second part of the error message containing the installation hint, should be removed.
> 
> And typing mistake in error message: Robotframework AIO

Hi Holger,

Thank you for your concern.
At the initial implementation of this feature, I also did not log the second part but there was a suggestion from @ThPoll to add that message ([3rd comment on Jira ticket](https://rb-tracker.bosch.com/tracker01/browse/ROBFW-195)).

However, that message contents the internal path which should not be in OSS version.

So, I think it should be better that we will remove it.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi both,
what is the status here?

> Hello Holger,
> 
> Version check now is optional according to new requirement from Thomas #54 From ROBFW-AIO version 0.6.0, version control mechanism is just activated in case user execute robot run with --variable version_check:${True}
> 
> By default, version check is deactivated.
> 
> Thank you, Son


I'm really confused:
There is no version_check variable wanted.

version check is be default not done if minimum- and maximum-version are not provided.
If a minimum-version is provided, then this is verified.
If a maximum-version is provided, then this is verified.
So the trigger for the verification is to set a minimum- and/or maximum-version.

Thank you,
 Thomas

**Comment by namsonx** [comment]
> Hi both, what is the status here?
> 
> > Hello Holger,
> > Version check now is optional according to new requirement from Thomas #54 From ROBFW-AIO version 0.6.0, version control mechanism is just activated in case user execute robot run with --variable version_check:${True}
> > By default, version check is deactivated.
> > Thank you, Son
> 
> I'm really confused: There is no version_check variable wanted.
> 
> version check is be default not done if minimum- and maximum-version are not provided. If a minimum-version is provided, then this is verified. If a maximum-version is provided, then this is verified. So the trigger for the verification is to set a minimum- and/or maximum-version.
> 
> Thank you, Thomas

Hello Thomas,

oh, sorry I misunderstood your requirement #54, I will update this version check

Thank you,
Son

**Comment by namsonx** [comment]
Hello Thomas and Holger,

I created new commits [6b7ec92e](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/73/commits/6b7ec92e9678fa02a3f85d8dfbe7643edae47505) and [32174b48](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/73/commits/32174b481e588d6b592991b7a47991d9e377d304) to revert and implement again requirement #54 

Thank you,
Son

**Comment by HolQue** [comment]
Does this include to do this:

```
  "Maximum_version" : null,
  "Minimum_version" : null,
```
?

**Comment by namsonx** [comment]
Hello Holger,

Currently, Max and Min version are optional, but Json schema is still checked in in case "Maximum_version" or "Minimum_version" is defined in configuration file.
We already defined these max and min versions must be string with pattern "^\\d+\\.\\d+\\.\\d+$".
In case you set null, it will throw the error message below:
[ ERROR ] Parameter 'Maximum_version' in JSON configuration file is not allowed due to: None is not of type 'string'
Test Dotdict Config Params 001                                        | UNKNOWN |
Variable '${CONFIG}' not found.

So, "null" currently does not include.

Thank you,
Son

**Comment by namsonx** [comment]
> Does this include to do this:
> 
> ```
>   "Maximum_version" : null,
>   "Minimum_version" : null,
> ```
> 
> ?

Hello Holger,

I created [new commit](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/73/commits/eb0b115b2b38c96d7d4db6d56c535c5efe0631b2) for pull-request #73, now "null" is allowed to set for max and min versions. And testsuitesmanagement does not check version in case these values are set "null".

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
important is, that it works also if nothing is provided. So, no Minimum_version/Maximim_version entry at all.
```
{
}
```
So you need to initialize the values already with **null** and then overwrite if provided.
Thank you,
 Thomas

**Comment by namsonx** [comment]
> Hi Son, important is, that it works also if nothing is provided. So, no Minimum_version/Maximim_version entry at all.
> 
> ```
> {
> }
> ```
> 
> So you need to initialize the values already with **null** and then overwrite if provided. Thank you, Thomas

Hello Thomas,

The current behavior is testsuitesmanagement works normal in case nothing is provided as you mentioned above.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Holger,
as yesterday discussed please create new issues for the issues you found.
It's difficult to follow multiple issues in one thread.
Thank you,
 Thomas

**Comment by HolQue** [comment]
done

**Comment by test-fullautomation** [comment]
Thank you.
The initial issue is solved => closed issue.
