### ISSUE TITLE
Outdated company name

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#72]
Files inside the `atest` folder still contain the in between outdated company name "Robert Bosch Car Multimedia GmbH".

This should be updated.

**Comment by test-fullautomation** [comment]
Hi Son,
this is a general issue of the whole package.
Please clean this up after 0.6.0
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

Do you want me to update the company name in this release 0.6.0?

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
No, this you can do with release which follows 0.6.0 as I have written before...
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Son,
what is the status of this issue?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
@namsonx : What is the status of this issue?

**Comment by namsonx** [comment]
I updated the header of the files in atest directory.

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
