### ISSUE TITLE
Unfavorable error message in case of invalid value

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#77]
In case of a parameter in a JSON configuration file has an invalid value or type

"Maximum_version" : "something invalid",

the error message tells that the parameter is not allowed:

[ ERROR ] Parameter 'Maximum_version' in JSON configuration file is not allowed due to: 'something invalid' does not match '^\\d+\\.\\d+\\.\\d+$'

But that's wrong. The parameter is allowed. It's the value that is not allowed or invalid.

The error message should reflect this properly.

Reference: Windows build job 1681416

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding, I created the pull-request #81 to update the error message log of Json schema validator.

Thank you,
Son

**Comment by HolQue** [comment]
Solved in 0.6.0.5
