### ISSUE TITLE
Improvement of version check feedback (good case)

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#78]
Because now the version check can be switched on and off I would like to have this mentioned in the log file.

Like:

* "Running without version check"
* "Version check passed"
* In case of version check failed => already implemented error message

Reference: Windows build job 1687142

**Comment by test-fullautomation** [comment]
postponed to version after 0.6.0 (0.6.1 or 0.7.0)

**Comment by namsonx** [comment]
Hello Holger,

I created the pull-request #110  for this enhancement request.

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and merged with #110
