### ISSUE TITLE
Improvement of version check feedback (bad case)

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#79]
Instead of:

The **configuration** requires minimum Robotframework AIO version ...

maybe it is better to focus on test execution with:

The **test execution** requires minimum RobotFramework AIO version ...

Because that's it! The configuration is only the place where the expected versions are defined. But it is not the configuration itself, that requires. The test execution does.

Reference: Windows build job 1687142

**Comment by namsonx** [comment]
Hello Holger,

I updated log output in case version conflict in the pull-request #81 

Thank you,
Son

**Comment by HolQue** [comment]
Solved with 0.6.0.5
