### ISSUE TITLE
testsuitesmanagement not executable anymore after sphinx maintenance

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-testsuitesmanagement#8]
Hi Son,

Holger maintained the sphinx project for the testsuitesmanagement .
Unfortunately it was required to change include paths (absolute to releative, ...).
As a result currently testsuitesmanagement is not running anymore.

Please maintain the code and please take very much care that the sphinx based html and latex build works still properly after your changes.

Please also refer to the commit messages from Holger:
"* !!! CAUTION: Import paths modified to resolve Sphinx errors (positions marked with "# Sphinx fix to be verified"). This modification needs to be verified !!!
* !!! CAUTION: Some docstrings commented out to resolve Sphinx errors (rst syntax issues). These docstrings need to be reworked !!! "

Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Son,

!!! please give me some more time before you start any activity !!! I overlooked some interdependencies. I am still learning but most probably the changes I made in your code are not necessary. I will come back to you soon when I have a valid solution.

**Comment by test-fullautomation** [comment]
Hi Son,
O.K. nothing to do here for the moment for you. Please wait for Holgers trigger.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Son,

with [9](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/9) I finished my maintenance activities. The import problem is solved at Sphinx level. The changes I made in your code are undone.

Please have a deeper look at two main fixes in setup.py: Now also subfolders and the additional json files are installed.

Maybe it's a good idea to do a full check of the functionality after all these changes.

Thank you

Holger

**Comment by HolQue** [comment]
I installed https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/9
based on alpha__RobotFramework_setup_vscode_apertis_rfw4.1__0.1.4.0.exe

Executing a robot file causes the following error message:
20220308 10:16:43.762 - FAIL - NameError: name 'RobotFramework_Testsuites' is not defined
20220308 10:16:43.763 - DEBUG - Traceback (most recent call last):
  File "D:\RobotFramework\python39\lib\site-packages\RobotFramework_Testsuites\__init__.py", line 63, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "D:\RobotFramework\python39\lib\site-packages\robotlibcore.py", line 94, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "D:\RobotFramework\python39\lib\site-packages\RobotFramework_Testsuites\Keywords\CSetup.py", line 37, in testsuite_setup
    if not RobotFramework_Testsuites.CTestsuitesCfg.oConfig.bLoadedCfg:

**Comment by namsonx** [comment]
Hello Holger,

    I have just test the functionality of Testsuites-Management package after your #9 was merged.
    Unfortunately, robot run failed due to "NameError: name 'RobotFramework_Testsuites' is not defined"
    In python module: ".../RobotFramework_Testsuites/Keywords/CSetup.py" line 17, could you please un-comment out "import RobotFramework_Testsuites" which you commented out in #6 ?

Thank you,
Son

**Comment by namsonx** [comment]
> I installed #9 based on alpha__RobotFramework_setup_vscode_apertis_rfw4.1__0.1.4.0.exe
> 
> Executing a robot file causes the following error message: 20220308 10:16:43.762 - FAIL - NameError: name 'RobotFramework_Testsuites' is not defined 20220308 10:16:43.763 - DEBUG - Traceback (most recent call last): File "D:\RobotFramework\python39\lib\site-packages\RobotFramework_Testsuites__init__.py", line 63, in run_keyword return DynamicCore.run_keyword(self, name, args, kwargs) File "D:\RobotFramework\python39\lib\site-packages\robotlibcore.py", line 94, in run_keyword return self.keywords[name](*args, **(kwargs or {})) File "D:\RobotFramework\python39\lib\site-packages\RobotFramework_Testsuites\Keywords\CSetup.py", line 37, in testsuite_setup if not RobotFramework_Testsuites.CTestsuitesCfg.oConfig.bLoadedCfg:

**Comment by HolQue** [comment]
Hmm - maybe I overlooked this position while undoing my changes. When I uncomment this line I am able to execute my test and the test is passed. But nevertheless in between the following error message occurs:

[ ERROR ] Calling method '_start_suite' of listener 'LibListener' failed: AttributeError: type object 'SuiteStructureBuilder' has no attribute 'data_sources'

I execute robotframework-extensions-collection\test\01.test.pretty_print.robot in a simple command line (batch file).

**Comment by test-fullautomation** [comment]
Hi Son,

O.K. Thank you for your reply. n

Now I need your help!
Please try to get testsuites-management run again. Please do the required changes.
Holger doesn't know about the function of the module, only about the documentation generator part.
So therefore we need to iteratively correct till both, code and documentation generator is working properly.
So, please fix and create a new pull request. This will then go to Holger again for check.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,
  
    I have just created the pull-request #10  to fix the issue "NameError: name 'RobotFramework_Testsuites' is not defined"
    I also did the functionality test and selftest for Testsuites-Management package (everything are working fine).
    
Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
Thank you, very good!
Thomas

**Comment by test-fullautomation** [comment]
Hi Holger,
I merged #10. Can you please check if Sphinx runs now properly.
(O.K. now we have also the new problem with the package naming)
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
This issue is solved.
