### ISSUE TITLE
Parameter check in JSON configuration file not sufficient

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#80]
With installed version 0.6.0 this causes an error (like expected):

"Minimum_version" : "0.9.0",

But in case of a user makes a typing mistake:

"Minimum_typing_mistake" : "0.9.0",

this is ignored completely. The version check does not fail!

Consequence: It is not sufficient to check if all required parameters are defined. It also has to be checked if the user defines
any other parameter, that is **not** supported. This would detect typing mistakes in optional parameters.

Reference: Windows build job 1687142

**Comment by test-fullautomation** [comment]
Hi Son,
I know that the JSON schema parser ignores keys which are not mentioned in the schema.
As already discussed at the beinning of testsuitesmanagement we need a solution for this.
If a key appears other than mentioned in the JSON schema, then we must create a meaningful error message.

This is relevant for 0.7.0.

Thank you,
 Thomas

**Comment by namsonx** [comment]
> 

Hello Thomas,

     I will find a solution for the case which Holger mentioned.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Thomas and Holger,

As our discussion in the meeting, we decided to disable the additional properties at the top level of json configuration file.
I created the tiny change for this issue #108 

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and already merged with #108
