### ISSUE TITLE
Unexpected type cast in log file

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#84]
Within a JSON configuration file I overwrite a parameter in the following way:

`${params}['global']['dict_val']['key_1']['subkey_11']['subsubkey_112'] : ${params}['global']['int_val'],`

This causes the following entry in log file:

`The parameter str(${params}['global']['dict_val']['key_1']['subkey_11']['subsubkey_112']) is updated`

The information itself is very useful but I wonder why the usage of a type cast like `str(...)` is also part of the log output.

Type castings are code internals and do not need to be logged.

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding, I will update it :)

**Comment by namsonx** [comment]
Hello Holger,

I created the pull-request #109  for this issue.

Thank you

**Comment by test-fullautomation** [comment]
solved and already merged with #109
