### ISSUE TITLE
Multiple version numbers

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#87]
The file
`RobotFramework_TestsuitesManagement\__init__.py`
introduces a version information
`__version__ = '0.0.1'`
that is passed to Robot Framework with
`ROBOT_LIBRARY_VERSION = __version__`
inside `class RobotFramework_TestsuitesManagement`

Why do we need a separate `__version__`?

We have already the package version defined in
`RobotFramework_TestsuitesManagement\packageversion.py`
with currently deviating number
`VERSION      = "0.3.0"`

The package version numbers should be aligned and only be placed at one position in the code, and not at several positions.

**Comment by namsonx** [comment]
Hello Holger and Thomas,

Thank you for your finding :)
At the beginning of testsuitesmanagement development, I planned to define version of this package library here in __init__.py
Then we decided to define version in Config\CConfig.py but I forgot to remove version define in RobotFramework_TestsuitesManagement\__init__.py

I created the pull-request #111 for this issue.

Thank you,
Son

**Comment by test-fullautomation** [comment]
already solved and merged with #111
