### ISSUE TITLE
merge contents of test and atest folders in this repo

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/robotframework-testsuitesmanagement#90]
Hi,

There are now 2 test folders **test** and **atest** in this repo.
They should be merged into 1 folder for the test execution.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
The folder ```test``` is created by holger.
The content from ```test``` need to be part of atest.

**Comment by namsonx** [comment]
Well noted!

**Comment by HolQue** [comment]
Please wait with merge.

Reason: I am currently using the test folder to explore some new test concepts (prototype development).

Status: The `atest `folder is the official one; the `test `folder is playground only.

Please give me ~1-2 weeks. I will give an update until the prototype is ready to use.

**Comment by test-fullautomation** [comment]
O.K. for me...

**Comment by test-fullautomation** [comment]
replaced with #150
