### ISSUE TITLE
Test execution with failed JSON schema validation

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#91]
In case of issues with `robot_schema.json` (syntax errors inside or file not existing) a proper error message is provided.

But even so the test is executed. Is this behavior like expected?

I would assume that we cannot trust test results if the JSON schema validation fails.

A schema violation must immediately stop test execution and result in "unknown".

**Comment by namsonx** [comment]
Hello Holger, 

Cuong had implemented this requirement in https://github.com/test-fullautomation/robotframework
Could you please pull the latest code of robotframework repository then check again?

.. code::
    ==============================================================================
    Exercise-06
    ==============================================================================
    [ ERROR ] Parameter 'Maximum_version' with invalid value found in JSON configuration file!
    '1.0.0.3' does not match '^\\d+\\.\\d+\\.\\d+$'
    Test Case exercise-06 :: exercise-06                                  | UNKNOWN |
    Parent suite setup unknown:
    Unknown exception occurs. Details: None
    ------------------------------------------------------------------------------
    Exercise-06                                                           | UNKNOWN |
    Suite setup unknown:
    Unknown exception occurs. Details: None
    
    1 test, 0 passed, 0 failed, 1 unknown
    ==============================================================================
    Debug:   c:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\debug_log.log
    Output:  c:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\output.xml
    Log:     c:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\log.html
    Report:  c:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\report.html

**Comment by HolQue** [comment]
Hi Son,

I am astonished. The RobotFramework_TestsuitesManagement installs the JSON schema file. And works with this file. Why is the fix not located in the RobotFramework_TestsuitesManagement? Why in a complete different repository?

**Comment by test-fullautomation** [comment]
Hi Holger,

unknown handling and stopping execution in case of unknown is task of the robotframework core.
Are you sure that you use our robotframework from 0.6.0.5 version?

Thank you,
 Thomas

**Comment by HolQue** [comment]
Installed is RobotFramework_AIO_setup_0.6.0.5 together with latest feature branches containing bugfixes.

Does setup_0.6.0.5 already support the execution abort in case of schema violations?

**Comment by HolQue** [comment]
The execution stop with result UNKNOWN itself is implemented in robotframework. OK. But the stop has to be triggered! And this has to happen in testsuites management - also in case of JSON schema issues.

This is missing!

In CConfig.py you have to add the missing

`BuiltIn().unknown()`

after

`logger.error(f"Could not parse configuration JSON schema file: '{str(err)}'")`

Then it works. Please check also other positions in the code where this may be required.

**Comment by test-fullautomation** [comment]
Hi Holger,

you are right, the trigger need to come from testsuites-management of course.
@namsonx: Please fix this.

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Please implement as agreed in #96

**Comment by HolQue** [comment]
Works with setup_0.7.0.4
Issue can be closed

**Comment by test-fullautomation** [comment]
Hi Son,
which pull-request contains the solution for this issue?
Thank you,
 Thomas
